### ISSUE TITLE
Expected to get |string| or |function| as the first argument, but got "false" instead.

### ISSUE THREAD

**Issue by brandoncordell** [Studiosity/grover#101]
I'm having issues getting `grover` working in my Rails app.

### Environment

* MacOS 10.15.6
* Ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
* Rails 6.0.3.4
* Grover ~> 0.14
* Webpacker 5.2.1
* Webpack 4.44.2
* Puppeteer 5.5.0

### config/initializers/grover.rb

```
# frozen_string_literal: true

Grover.configure do |config|
  config.options = {
    format: 'A4',
    full_page: true,
    execute_script: true,
    margin: {
      top: 10,
      right: 10,
      bottom: 10,
      left: 10
    },
    viewport: {
      width: 1000,
      height: 2950
    },
    prefer_css_page_size: true,
    emulate_media: 'screen',
    cache: false,
    # timeout: 0, # Timeout in ms. A value of `0` means 'no timeout'
    launch_args: ['--font-render-hinting=medium'],
    wait_until: 'networkidle0'
  }
end

```
### PdfsController

```
# frozen_string_literal: true

module Pro
  module Game
    class PdfsController < ApplicationController
      skip_authorization_check

      before_action :load_report

      def new
        attach_pdf

        redirect_to url_for(@game_report.pdf)
      end

      def show
        attach_pdf unless @game_report.pdf.attached?

        redirect_to url_for(@game_report.pdf)
      end

      private

      def attach_pdf
        pdf_from_string

        # @game_report.pdf.attach(
        #   io: StringIO.new(pdf_from_string),
        #   filename: "game_report_#{@game_report.id}_#{Time.zone.now}",
        #   content_type: 'application/pdf'
        # )
      end

      def load_report
        @game_report = Report.includes_associations.find(params[:report_id]).decorate
      end

      def pdf_from_string
        base_url = "#{request.protocol}#{request.host_with_port}/"
        processed_html = Grover::HTMLPreprocessor.process(pdf_string, base_url, request.protocol)

        grover_options = {
          display_url: request.referer,
          execute_script: false,
          cache: true,
          timeout: 50_000
          # timeout: 0,
          # debug: {
          #   headless: false,
          #   devtools: false
          # },
          # wait_until: 'domcontentloaded'
        }

        Grover.new(processed_html, grover_options).to_pdf
      end

      def pdf_string
        ReportsController.new.render_to_string(
          template: 'pro/game/reports/show',
          formats: :pdf,
          layout: 'pro/game/reports',
          locals: { '@game_report': @game_report }
        )
      end
    end
  end
end
```

I've confirmed the `processed_html` is indeed a string. This gets passed into the initializer but somewhere between the initializer and `to_pdf` something goes awry.

**Comment by abrom** [comment]
I suspect it's because you're passing `false` through to `executeScript` in your `pdf_from_string ` method which is expecting a string type (albeit without type-checking)

```
execute_script: false,
```

**Comment by abrom** [comment]
Per the docs:
```
Javascript can be executed on the page (after render and before conversion to PDF/image) with the execute_script option.
```
If that isn't clear enough I'd be happy to accept a PR that reworded it to be as such.

**Comment by brandoncordell** [comment]
Thanks @abrom. It makes sense to me now but in my head when I read through the README I took that as a boolean option whether to execute the scripts already included in the html for the PDF. The `execute_script` option is for custom javascript at the config level?

**Comment by brandoncordell** [comment]
@abrom I've fixed the error (thank you!) but now my PDF just times out.

Here's my layout

```
!!!
%html{ lang: 'en' }
  %head
    %meta{ charset: 'utf-8' }
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1.0' }

    = stylesheet_pack_tag 'application_v2', 'pro/game/reports', media: 'all'
    = javascript_pack_tag 'application_v2', 'pro/game/reports'
    -# %link{ href: 'https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css', rel: 'stylesheet' }
  %body
    = yield
```

If I include my packs, the request will just time out (or seemingly run forever) but if I comment out the pack lines the PDF loads immediately. The links to the assets are absolute thanks to the processor. The links work in my normal browser but in chromium trying to open an asset in another tab just spins as well (this may be because it's trying to load the PDF though).

If I set `devtools` to true the only thing that ever gets loaded is the head of the page. `<body>` never gets loaded.

**Comment by abrom** [comment]
The `execute_script` option is for executing javascript on the page (after render and before conversion).

Can you confirm you've got at least __two__ Rails workers? Remember when you're requesting a PDF to be generated you're making a request, which is itself may then be making subsequent requests to fetch your assets (images, stylesheets and javascript etc).. Your layout suggests you are indeed going to be requesting assets..

**Comment by abrom** [comment]
If you only have one worker then the subsequent requests will be sitting there waiting for an available worker.. which will never happen because you're currently using it to request the PDF!

**Comment by brandoncordell** [comment]
Here is my puma config

```
workers Integer(ENV.fetch('WEB_CONCURRENCY') { 5 })
threads_count = ENV.fetch('RAILS_MAX_THREADS') { 1 }
threads threads_count, threads_count

preload_app!

rackup DefaultRackup
port        ENV.fetch('PORT') { 3000 }
environment ENV.fetch('RAILS_ENV') { 'development' }

on_worker_boot do
  ActiveSupport.on_load(:active_record) do
    ActiveRecord::Base.establish_connection
  end
end
```
