### ISSUE TITLE
Css background-image won't ever show

### ISSUE THREAD

**Issue by Moltenhead** [Studiosity/grover#103]
So I'm using your gem trying to generate cards for a proto game.
Works fine and all and sufficiently documented but only problem, I'm using background-image: url() css rule to display repeted concepts (borders, keywords, and others ...) and all those won't show.
Also using an img tag and images also won't display within the final render.

I've tried using those paramaters for to_png with no success : 

- wait_until: %w[load domcontentloaded]
- timeout: 0
- omit_background: true
- print_background: true
- full_page: true

```ruby
grover = Grover.new(converted_html, wait_until: %w[load domcontentloaded], timeout: 0, omit_background: true, print_background: true, full_page: true)

# [...]

grover.to_png(local_path)
```

I can't seem to find anything more that could prevent background image to display, or maybe the pupppeteer "screenshot" is taken before the images get fully loaded. Any idea about how to resolve this ?

**Comment by abrom** [comment]
it's likely just chromium deciding that you shouldn't have image backgrounds when printing (an ink saving measure).

Try add this to your styles:
```
@media all {
  -webkit-print-color-adjust: exact;
}
```

**Comment by Moltenhead** [comment]
I'm having another issue : 
`*** Grover::JavaScript::Error Exception: Unknown value for options.waitUntil: domcotentloaded`
I quadruple checked my code and `domcotent` is never set, but `domcontent` is set twice : 

- within `config/initializers/grover.rb`
```ruby
# frozen_string_literal: true

# config/initializers/grover.rb
Grover.configure do |config|
  config.options = {
    # format: 'A4',
    # margin: {
    # top: '5px',
    # bottom: '10cm'
    # },
    # viewport: {
    #   width: 640,
    #   height: 480
    # },
    # prefer_css_page_size: true,
    # emulate_media: 'screen',
    # cache: false,
    # timeout: 0, # Timeout in ms. A value of `0` means 'no timeout'
    # launch_args: ['--font-render-hinting=medium'],
    wait_until: %w[load domcontentloaded]
    # print_background: 'true'
    # debug: {
    #   headless: false,  # Default true. When set to false, the Chromium browser will be displayed
    #   devtools: true    # Default false. When set to true, the browser devtools will be displayed.
    # }
  }
end
```
- at `Grover` instanciation
```ruby
    grover = Grover.new(
            converted_html,
            wait_until: %w[load domcontentloaded],
            timeout: 0,
            omit_background: true,
            print_background: true,
            full_page: true
            # viewport: {
            #   width: 640,
            #   height: 480
            # }
          )
```

I'll try without but seems to be a bug.

**Comment by Moltenhead** [comment]
Hi. back thx for the respond.
I can't try this since the app just decided to need a yarn install to launche correctly - npm did the trick yesterday.
Now the gem just won't succeed generating the png at all.
Tested within byebug and no matter what I do, puppeteer triggers, open the page (which is totaly blank even with `@medial all{*{-webkit-print-color-adjust: exact;}}`), then returns nil.

**Comment by abrom** [comment]
Grover is a pretty thin wrapper around Puppeteer (which then calls out to Chromium, Chrome or Firefox). If i'm reading your message correctly it sounds like when using Chromium it works fine, but you're having issues with Firefox? I can't say I've tested Puppeteer with Firefox, but this doesn't sound like an issue with Grover. You should be able to test our your styles etc by just loading up the HTML content in the browser of choice and going to the print view (or potentially using the browser inspector to apply the print media type).

**Comment by Moltenhead** [comment]
Yep. Thanks for the help anyway. Definitly not from Grover just have to find some fix for this css shenanigan.
Is there references somewhere about how to specify a navigator for Grover to use ?

**Comment by abrom** [comment]
By navigator are you talking about the browser that Puppeteer uses?

You can specify the `PUPPETEER_EXECUTABLE_PATH` and `PUPPETEER_PRODUCT` per https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#environment-variables

There is the option for passing through the `executable_path` option (just like any other option), but there is no `product` option yet so that would need to be passed through as an ENV param.

**Comment by Moltenhead** [comment]
Perfect that's exactly what I was searching for. And yeah navigator is a frenchism sorry. ^^
Anyway thanks for the support I think I can handle this on my side now and btw to let you know :

```css
@media print{
  *{
    -webkit-print-color-adjust: exact;
    color-adjust: exact;
  }
}
```

Could resolve some print view issue for others, the not webkit rule is consumed by firefox while the other by IE and chrome.
Keep on the good work.

**Comment by Moltenhead** [comment]
Welp sorry to bother again but I've manually tweaked your gem to prevent it to close the chromium window during the ensure block within `processor.js` l.122.
And I've just find why nothing is displaying within the browser, that's coming from access right issues - found those 3 errors within the puppeteer page :

```
converted.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
favicon.ico:1 GET http://example.com/favicon.ico 404 (Not Found)
carlo-varese.jpg:1 GET http://example.com/path/to.jpg 404 (Not Found)
```

I have then tried to open the same produced html within the same browser and it doesn't has any trouble loading the css and the image.
I'll try to find how to correct this but if you have any idea I'll be happy to read it.

**Comment by abrom** [comment]
I see your browser is trying to fetch the assets from `example.com`. Likely issue is:

https://github.com/Studiosity/grover#relative-paths

**Comment by Moltenhead** [comment]
Tested to use `relative-paths` but :
In my case I am generating an html file through code, then try to call local images through puppeteer.
Tried to edit the href and sources to use the `file://` argument at beginning to ensure absolute path, problem : 
The generated page can't access the path because of security restrictions from distant servers - the puppeteer page is considered as a distant server.

I think I'll just start a Rails server and handle the display through it then set the Grover first param to be the Rails app url.
I don't see any other way to bypass this issue. But maybe I lack knowledge about puppeteer.

**Comment by abrom** [comment]
Right. Grover simply wraps Puppeteer which calls out to the browser. If the browser can't load the assets (ie make a web request) then the other alternative would be to inject your assets into the source HTML. Ie base64 encode your images (and inject inline) and inject any CSS and JS into the HTML inline. But that's up to you :)

**Comment by Moltenhead** [comment]
That's a fair point, I'll consider both options. Thanks for the help again.
