### ISSUE TITLE
Most common encoding issues ?

### ISSUE THREAD

**Issue by Moltenhead** [Studiosity/grover#104]
Just to know if there is some common encoding issues with Grover.
I'm successfully generating pngs from full image content, but having some \xD3 ASCII-8BIT to UTF-8 and other of the kind conversion errors with combined text and images produced from grover - haven't tried yet with non grover produced images.

Tried to force encoding at every step (within js and rb processors, within grover rb and at every steps of my process).
I'm also having those without specifying a path for conversion, I've tried using `to_png` and `to_pdf`. Seems that the error triggers after most of the return chain, it even was able to print within the `Grover.screenshot` before triggering.

The trigger seems to be a `write` method that ruby is telling me I have in my code, though the line at which it points is the Grover to_png / to_pdf method, and the only `write` method I could traceback was within the js processor. But the error triggers far after it is called and has produced something.

Also the consumed htmls are displaying correctly from the point where Grover is calling them (Rails erb view tested through preventing puppeteer browser closing).

But nothing seems to do right now. Will keep on tomorrow with different htmls and different ways of producing them ... right now I need some sleep.

**Comment by abrom** [comment]
Hmm I haven't seen this sort of issue in Grover before. It would be useful to see some stack traces. Are you able to create a small test case demonstrating the problem?

**Comment by olegsobchuk** [comment]
@Moltenhead I faced an encoding issue in  case when I tried to generate PDF from rails console
so this code raise encoding exceprion
```
pdf = grover.to_pdf; nil
File.open('res.pdf', 'w') { |f| f.write(pdf) }
```
after adding `.force_encoding("utf-8")` it saves file as expected

```
pdf = grover.to_pdf; nil
File.open('res.pdf', 'w') { |f| f.write(pdf).force_encoding("utf-8") }
```

**Comment by abrom** [comment]
any reason you can't just have Grover save it for you? ie `grover.to_pdf 'res.pdf'`.

You can also pass the path in via the initialiser:
```
Grover.new(....., path: 'res.pdf').to_pdf
```

**Comment by olegsobchuk** [comment]
@abrom  you'r right, thanks

**Comment by Moltenhead** [comment]
Can't work on it right now. But will try asap. Thanks for the help.

**Comment by Moltenhead** [comment]
So I've been able to generate documents using the `path` option at Grover instantiation. But still get an encoding error whenever rails console tries to display whatever the method returns I suppose. So this is not from Grover per say, but more from rails console display shenanigans. Already happened to me previously with some other encoding conversion problems ... I don't have time to investigate more of it right now, but at least Grover isn't seem to be the culprit ; the generated pdf is as I expect it to be.
