### ISSUE TITLE
About addStyleTag and addScriptTag

### ISSUE THREAD

**Issue by RanX12** [Studiosity/grover#109]
Hi, @abrom
Maybe this is not a bug, but a question of mine. My scss and js files are not valid in the PDF file.
I have tried the following code:
```ruby
  def edit
    pdf_html = render_to_string(template: 'teams/written_pad_reports/show', layout: 'pdf.html.slim', )

    base_url = "#{request.protocol}#{request.host_with_port}/"
    grover_options = {
      display_url: base_url,
      format: 'A4',
      print_background: true,
    }

    pdf = Grover.new(pdf_html, grover_options).to_pdf
    send_data pdf, filename: "#{test}.pdf", type: 'application/pdf'
  end
```
and
```ruby
  def edit
    pdf_html = render_to_string(template: 'teams/written_pad_reports/show', layout: 'pdf.html.slim', )
    pdf = Grover.new(pdf_html).to_pdf
    send_data pdf, filename: "#{test}.pdf", type: 'application/pdf'
  end
```
my html code:
![image](https://user-images.githubusercontent.com/46048444/112279014-628cc680-8cbe-11eb-8422-62ca87c8a3a8.png)
Neither css nor js takes effect, Then I saw your ```style_tag_options```, ```script_tag_options```
But now I don't quite understand, how should I write these two options
I have tried to write like this:
```ruby
script_tag_options = [
  { url: 'http://localhost:3000/packs/css/application.js' },
  { path: 'application.js' }
]
style_tag_options = [
  { url: 'http://localhost:3000/packs/css/application.css' },
  { path: 'application.css' }
]
```
It won't work！(They are in webpacker)
Could you please advise？

**Comment by abrom** [comment]
The likely issue here is going to be relative paths. Your `stylesheet_pack_tag` and `javascript_pack_tag` methods are going to reference the assets relative to your application. So it won't matter if you request from `localhost` or `my.awesome.domain`. As a result, when loading the HTML, the web browser won't know how to resolve the assets properly, and they won't load.

There is a section in the documentation that talks about this: https://github.com/Studiosity/grover#relative-paths

Essentially you'll need to do something like:
```
absolute_html = Grover::HTMLPreprocessor.process pdf_html, base_url, request.protocol
```
then pass the `absolute_html` into Grover.

Also useful is the section on debugging: https://github.com/Studiosity/grover#debugging

You can have the browser display itself and view the devtools to debug network requests etc etc.

Also note, be sure to have at least __2__ workers available on your web server. One will be needed for the original request, then there will need to be at least one other worker to handle the asset requests. If you only have one worker it will just sit there until the original request times out waiting for a worker to become available to handle the asset requests.

**Comment by RanX12** [comment]
> The likely issue here is going to be relative paths. Your `stylesheet_pack_tag` and `javascript_pack_tag` methods are going to reference the assets relative to your application. So it won't matter if you request from `localhost` or `my.awesome.domain`. As a result, when loading the HTML, the web browser won't know how to resolve the assets properly, and they won't load.
> 
> There is a section in the documentation that talks about this: https://github.com/Studiosity/grover#relative-paths
> 
> Essentially you'll need to do something like:
> 
> ```
> absolute_html = Grover::HTMLPreprocessor.process pdf_html, base_url, request.protocol
> ```
> 
> then pass the `absolute_html` into Grover.
> 
> Also useful is the section on debugging: https://github.com/Studiosity/grover#debugging
> 
> You can have the browser display itself and view the devtools to debug network requests etc etc.
> 
> Also note, be sure to have at least **2** workers available on your web server. One will be needed for the original request, then there will need to be at least one other worker to handle the asset requests. If you only have one worker it will just sit there until the original request times out waiting for a worker to become available to handle the asset requests.

yeah，Yes, I also tried this kind of code:
```ruby
def edit
    base_url = "#{request.protocol}#{request.host_with_port}/"
    pdf_html = render_to_string(template: 'teams/written_pad_reports/show', layout: 'pdf.html.slim', )
    absolute_html = Grover::HTMLPreprocessor.process(pdf_html, base_url, request.protocol)
    pdf = Grover.new(absolute_html).to_pdf
    send_data pdf, filename: "test.pdf", type: 'application/pdf'
 end
```
But my style and js still didn't work.

**Comment by abrom** [comment]
And what did the devtools (using debugging options) show?

**Comment by RanX12** [comment]
> And what did the devtools (using debugging options) show?

![image](https://user-images.githubusercontent.com/46048444/112434491-a21ae780-8d7e-11eb-9f9b-b52f9b31fb92.png)
There are no errors in the console

**Comment by abrom** [comment]
i'd be looking at the Network tab to see what the responses are (look to see the actual assets are being returned). Then check that your JS is loading/running by putting some debug output in there (`console.log('JS loaded')` or similar). Finally, check that your styles apply with the `print` media type (default in Chromium for exporting PDFs). If you want it to use `screen` you need to explicitly tell Grover to do so!! ie `emulate_media: 'screen'` in the options.

**Comment by abrom** [comment]
and of course if your issue is that background colours aren't rendered (also default when printing/exporting PDF in Chromium) you'd need to explicitly tell Chromium to render the colours:

```
body {
  -webkit-print-color-adjust: exact !important;
}
```
(or possibly use a more specific selector if need be)

**Comment by RanX12** [comment]
> 我会在“网络”标签中查看响应，以查看响应（查看返回的实际资产）。然后通过在其中（`console.log('JS loaded')`或类似位置）放置一些调试输出来检查JS是否正在加载/正在运行。最后，检查您的样式是否适用于`print`媒体类型（Chromium中默认用于导出PDF）。如果要使用它，则`screen`需要明确告诉Grover这样做！即`emulate_media: 'screen'`在选项中。
I have to add:
```emulate_media:'screen'```
Let me give you an example. My style on the web page looks like this:
![image](https://user-images.githubusercontent.com/46048444/112437879-684be000-8d82-11eb-93e9-b11965e08172.png)

But in PDF or Chormium, style and JS are not effective. . .
![image](https://user-images.githubusercontent.com/46048444/112437917-73067500-8d82-11eb-9b99-9d8ef7e4c3a6.png)

There is neither JS nor style. I have a console.log('========') in my JS, but it does not print in Chormium
![image](https://user-images.githubusercontent.com/46048444/112438669-1d7e9800-8d83-11eb-847d-d72399a8b946.png)

![image](https://user-images.githubusercontent.com/46048444/112438685-240d0f80-8d83-11eb-9dc1-99e6858ea986.png)

**Comment by RanX12** [comment]
> i'd be looking at the Network tab to see what the responses are (look to see the actual assets are being returned). Then check that your JS is loading/running by putting some debug output in there (`console.log('JS loaded')` or similar). Finally, check that your styles apply with the `print` media type (default in Chromium for exporting PDFs). If you want it to use `screen` you need to explicitly tell Grover to do so!! ie `emulate_media: 'screen'` in the options.

I have to add:
```emulate_media:'screen'```
Let me give you an example. My style on the web page looks like this:
![image](https://user-images.githubusercontent.com/46048444/112437879-684be000-8d82-11eb-93e9-b11965e08172.png)

But in PDF or Chormium, style and JS are not effective. . .
![image](https://user-images.githubusercontent.com/46048444/112437917-73067500-8d82-11eb-9b99-9d8ef7e4c3a6.png)

There is neither JS nor style. I have a console.log('========') in my JS, but it does not print in Chormium
![image](https://user-images.githubusercontent.com/46048444/112438669-1d7e9800-8d83-11eb-847d-d72399a8b946.png)

![image](https://user-images.githubusercontent.com/46048444/112438685-240d0f80-8d83-11eb-9dc1-99e6858ea986.png)

**Comment by abrom** [comment]
You appear to have your console log inside an event handler. Are you sure the event handler would load in that context? Try move it outside.

What happens if you put inline script or style tags, do they run/render? ie `<script>console.log('inline works')</script>` or `<style>body { background: blue }</style>`.

I'm not sure what you mean by:

> I have to add:
> emulate_media:'screen'

Are you saying you have tried that?

**Comment by RanX12** [comment]
> You appear to have your console log inside an event handler. Are you sure the event handler would load in that context? Try move it outside.
> 
> What happens if you put inline script or style tags, do they run/render? ie `<script>console.log('inline works')</script>` or `<style>body { background: blue }</style>`.
> 

Using ```<script>console.log('inline works')</script>``` is possible, but using ```javascript_pack_tag``` and ```stylesheet_pack_tag``` will not take effect
![image](https://user-images.githubusercontent.com/46048444/112440365-2d977700-8d85-11eb-9084-3b5dfd67e7f6.png)

![image](https://user-images.githubusercontent.com/46048444/112440327-240e0f00-8d85-11eb-90df-f20e824f244f.png)

> I'm not sure what you mean by:
> 
> > I have to add:
> > emulate_media:'screen'
> 
> Are you saying you have tried that?
yeah

**Comment by abrom** [comment]
have you tried putting the console log outside of the `turbolinks:load` event handler? Are you sure it is firing? I don't know how Chromium would behave for things like turbolinks etc when trying to emulate print.

**Comment by abrom** [comment]
And have you tried inline styles?

For the styles issue, suggest try inspect an element in the browser where it works.. see what the selector is (in full). Compare that to the styles applied to your debugger devtools. I.e. go to the Chromium `Rendering` tab and check what CSS media type is selected. Try change it.

**Comment by RanX12** [comment]
> And have you tried inline styles?
> 
> For the styles issue, suggest try inspect an element in the browser where it works.. see what the selector is (in full). Compare that to the styles applied to your debugger devtools. I.e. go to the Chromium `Rendering` tab and check what CSS media type is selected. Try change it.

```inline styles``` and ```inline script``` are effective, but in my project, I have to use webpack to deal with ```styles``` and ```script```

**Comment by artur79** [comment]
I'v struggled a lot with css loading issue also probably because my setup is webpacker assets and Docker, for now quick workaround is:
```
= javascript_pack_tag ‘pdf’, ‘data-turbolinks-track’: ‘reload’, host: ‘webpacker:3035’
= stylesheet_pack_tag ‘pdf’, media: ‘all’, ‘data-turbolinks-track’: ‘reload’, host: ‘webpacker:3035’
``` 
It does not require preprocessing approach mentioned above (Grover::HTMLPreprocessor ... and stuff), you can just use it with basic middleware approach.

To make it more flexible just use for dev env:
```
= Webpacker.dev_server.host
= Webpacker.dev_server.port
```

**Comment by abrom** [comment]
I would happily accept a PR to update the README if it would help clarify this issue for other people

**Comment by RanX12** [comment]
> I'v struggled a lot with css loading issue also probably because my setup is css/js from webpacker plus Docker, for now quick workaround is:
> 
> ```
> = javascript_pack_tag ‘pdf’, ‘data-turbolinks-track’: ‘reload’, host: ‘webpacker:3035’
> = stylesheet_pack_tag ‘pdf’, media: ‘all’, ‘data-turbolinks-track’: ‘reload’, host: ‘webpacker:3035’
> ```
> 
> It does not require preprocessing approach mentioned above (Grover::HTMLPreprocessor ... and stuff), you can just use it with basic middleware approach.
> 
> To make it more flexible just use for dev env:
> 
> ```
> = Webpacker.dev_server.host
> = Webpacker.dev_server.port
> ```

thx，I ended up using wicked_pdf, because I finally solved the problem of wicked_pdf and webpacker that caused the download of PDF to get stuck.
