### ISSUE TITLE
Simple way to make the pdf landscape

### ISSUE THREAD

**Issue by ChrisMuga** [Studiosity/grover#111]
The pdf created using 

```ruby
pdf = Grover.new(html, options).to_pdf
```

will create a `portrait` PDF. Any way I can make a `landscape` one?

**Comment by ChrisMuga** [comment]
i had to pass `options` as:
```ruby
options = { landscape: true }
```

**Comment by abrom** [comment]
Correct! That is passed into the `page.pdf` method when creating the PDF. See https://github.com/puppeteer/puppeteer/blob/v9.0.0/docs/api.md#pagepdfoptions

That option can be passed through the global configuration, through the `Grover` initialiser or you can configure it per page (if you were say using the PDF middleware) using a meta tag:
```
<meta name="grover-landscape" content="true">
```
