### ISSUE TITLE
PDF renders with system fonts in Production, but with correct fonts in Development....

### ISSUE THREAD

**Issue by k2director** [Studiosity/grover#114]
HI there, did some browsing through old Issues but didn't see anything that suggested a solution. I'm using Grover/Puppeteer to render a PDF from a View file, and it renders fine in Development, but in Production, running from a Digital Ocean server, it's rendering out using lousy Mac fonts. 

I declare my Google fonts in my Application.html.erb file, and I have a no-frills call on Grover, both of which seem pretty standard.

Any guidance appreciated, thanks very much!!

H 

**APPLICATION.HTML.ERB**

`<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,300;0,600;0,700&display=swap" rel="stylesheet">
    <style>
      #menu-toggle:checked + #menu{
      display: block;
      }
    </style>
  </head>
  <body class="font-poppins">
    <%= render 'layouts/navbar' %>
    <div class="mx-4 my-20 md:mx-12 md:my-20">
      <%= yield %>
    </div>
  </body>
</html>
`

P.S. Okay, Github is stripping out some of my html above, like this line: 
link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,300;0,600;0,700&display=swap" rel="stylesheet"

**CONTROLLER CODE**

        base_url = 'https://www.easyinvoices.io/'
        html_absolute = Grover::HTMLPreprocessor.process html_relative, base_url, 'https'

      pdf = Grover.new(html_absolute, {
                         #  format: 'A4' hknote: default is Letter, so I commented this out,
                         margin: {
                           top: '2cm',
                           bottom: '2cm',
                           left: '2cm',
                           right: '2cm'
                         },
                         display_url: base_url
                       }).to_pdf

**Comment by abrom** [comment]
Hi @k2director hmm that's certainly an odd one. Is there any chance that the "Poppins" font (or at least something called "Poppins") may be installed on the DO server? (thus not actually downloading the Google sourced font) Suggest try run `fc-list` on the machine to see what you've got:

https://linux.die.net/man/1/fc-list

Does it do the same thing with a different font ? Say using a system installed font.. 

Does it do the same thing if you host the font on that machine?  I.e is there a chance there is some sort of outbound firewall rule that's stopping the remote font from being loaded? Suggest try enable the `raise_on_request_failure` option (ie `raise_on_request_failure: true`) which will raise an error if there are any issues on that front. Note this was only added in v1.0.1

The default load behaviour for Grover is to wait until there have been no network requests for 500ms so that shouldn't be the problem (assuming the network requests are succeeding). 

Can you confirm the OS you're testing on and the DO one are the same? Can you confirm the Puppeteer versions and Chromium versions are the same? Fonts rendered on different systems can result in very different results

**Comment by k2director** [comment]
Hi Abrom, thanks much for the reply and sorry for delay....just got back from a little summer vacation! 

So after going through some of your tips, it looks like I solved the problem but it created another smaller problem. 

The solution to my problem was to add "class=font-poppins" to my pdf.html.erb file's Body tag. I already had a link href pointing to that Google font in my pdf.html.erb file, but I didn't assign a Tailwind font class to the Body tag, so now I did and Development and Production are printing the same proper fonts in PDFs. I already had this in my Application.html.erb file, but had forgotten about the Pdf.html.erb file in my Layouts folder. Yay!

Now, the smaller problem I notice is that the PDF prints are adding excess letter spacing to some words, whereas the letter spacing on screen looks fine (screen shots attached).  I couldn't find any Grover issues addressing weird letter/character spacing. Any idea what might be going on?? 

Thanks again for your detailed help!

H

<img width="621" alt="screen_letter_spacing" src="https://user-images.githubusercontent.com/58047065/124527578-cdb85f80-ddba-11eb-86c7-1347b4071d89.png">

<img width="621" alt="pdf_letter_spacing" src="https://user-images.githubusercontent.com/58047065/124527581-d14be680-ddba-11eb-8adc-ac3d3b8f49f0.png">

**Comment by abrom** [comment]
Glad to hear it.

Hmm the letter spacing is an odd one. I would have said it was a [letter-spacing](https://developer.mozilla.org/en-US/docs/Web/CSS/letter-spacing) issue, however that would traditionally also increase the spacing of the spaces too! It looks more like a font issue. I would say it was a [mono-spaced font](https://en.wikipedia.org/wiki/Monospaced_font) but the `i`'s are clearly proportional. It may be some weird [font kerning](https://developer.mozilla.org/en-US/docs/Web/CSS/font-kerning) ??

I can't say why the display would be different.. possibly relates to https://github.com/itfoundry/Poppins/issues/22 however i'm no font expert. 

Does it do the same thing with other fonts?

**Comment by k2director** [comment]
Thanks Abrom. Okay, I'm going to explore the kerning issue separately, and will probably start by changing fonts and seeing what happens. In any event, we got my original problem solved, and so I will close this issue. Thanks much!

**Comment by wnm** [comment]
@k2director did you find a solution for your problem? how did you debug this? I'm having the same issue: distorted fonts i production. Its working well in development, and the problem is only in the page footer, the rest of the document has the same fonts, but no issues...
