### ISSUE TITLE
New PDF Page for every looping HTML

### ISSUE THREAD

**Issue by kori22** [Studiosity/grover#118]
hi, currently our project used pdf file report using grover, this gem is amazing, but currently we have problem with cleanest pdf report while using loop each data, this my result screenshot
<img width="818" alt="Screen Shot 2021-08-04 at 12 19 13" src="https://user-images.githubusercontent.com/6101157/128126309-ff18efe6-39e4-47b6-a687-acd6cc3e2287.png">

our espectaion is while looping new data, pdf will create new page, so the result will be clean
thanks

**Comment by abrom** [comment]
I expect you're going to want to take a look at https://developer.mozilla.org/en-US/docs/Web/CSS/break-after

On the element wrapping each section you'd add CSS style `break-after: page`. Note this is the same as `page-break-after: always` although `page-break-after` is a legacy property so better to use `break-after` 

For more details please try https://www.google.com/search?q=html+print+page+break

**Comment by kori22** [comment]
oh thanks, its works
