### ISSUE TITLE
Background images not printing through middleware

### ISSUE THREAD

**Issue by Richacinas** [Studiosity/grover#12]
Hi again,

After trying to convert to PDF a more complex HTML set, I suspect that the property print_background is not being properly passed to Puppeteer, or maybe there is a timeout problem.

Here is a **WORKING** example:

```
grover = Grover.new('<html><body><div style="display: block; width: 300px; height: 300px; background-image: url(https://statics.memondo.com/p/99/cfs/2017/12/CF_57532_33c1af8a2ba0422f9d908b927670e9e9_perros_cuando_no_sabes_si_tienes_una_foquita_o_un_perrete.jpg);background-size:cover"></div></body></html>'
)

grover.to_pdf
```

Here is a **NOT WORKING** example:

```
render(:inline => '<html><body><div style="display: block; width: 300px; height: 300px; background-image: url(https://statics.memondo.com/p/99/cfs/2017/12/CF_57532_33c1af8a2ba0422f9d908b927670e9e9_perros_cuando_no_sabes_si_tienes_una_foquita_o_un_perrete.jpg);background-size:cover"></div></body></html>', :layout => 'layout_pdf')
```

I went on to change the gem a little bit so I can see (print to rails console) exactly what options is Puppeteer getting after the normalize that you run through them, and it looks exactly the same on both cases:

**grover.rb (line 127)**

`puts normalized_options`

**And I get this:**

`{"displayUrl"=>"http://app.dev.informa/es/informe_pdfkit/informe_comercial/3193516/informe_comercial_A80192727", "format"=>"A4", "margin"=>{"top"=>"0.8in", "bottom"=>"0.65in", "right"=>"0.45in", "left"=>"0.5in"}, "preferCSSPageSize"=>true, "displayHeaderFooter"=>true, "printBackground"=>true, "emulateMedia"=>"print", "cache"=>false, "timeout"=>0}`

As you can see, I  pass the print_background option so Puppeter should be getting it and returning the PDF with background images.

Do you have an idea what could be happening here? I tried with Puppeteer alone, passing the same html string and it works perfectly.

Thank you very much..

**Comment by abrom** [comment]
If I use the same example you provided, passing through the `print_background` option via the configure block or via meta tags, and it works for me. I'm not sure what's in your `layout_pdf` layout, so I just used `layout: false`.

Can you tell me what you mean by "not working"?

**Comment by Richacinas** [comment]
You are right, it was something about my styles that I'm calling from `layout_pdf`.

:disappointed: so sorry!
