### ISSUE TITLE
[Feature Request] stylesheet_link_tag helpers that are compatible

### ISSUE THREAD

**Issue by jamesst20** [Studiosity/grover#120]
Hi,

a nice feature from the gem WickedPDF (https://github.com/mileszs/wicked_pdf) that uses wkhtmltopdf behind the scene is that they provide helper methods that are compatible with PDF:

```
wicked_pdf_stylesheet_link_tag # stylesheet_link_tag
wicked_pdf_javascript_include_tag # javascript_include_tag
wicked_pdf_stylesheet_pack_tag # stylesheet_pack_tag
wicked_pdf_javascript_pack_tag # javascript_pack_tag
image_tag wicked_pdf_asset_pack_path("media/images/foobar.png")
```

My request would be to provide a similar implementation but in the 'Grover' gem.

**Workaround**

I am currently using Grover to generate my PDF, but I also installed the WickedPDF gem and I included in my application.pdf.haml those 2 lines

```
= wicked_pdf_stylesheet_pack_tag 'application'
= wicked_pdf_javascript_pack_tag 'application'
```

and it is working perfectly.

**Comment by abrom** [comment]
First I think it's best to understand exactly what those methods are actually doing, and subsequently what benefit they bring. 

As far as I can tell they're either downloading or fetching from local asset mechanisms with specified asset, then injecting it into the response. Does that sound about right?

If that is the case, I'm not seeing a whole heap of benefits here. It also doesn't feel like it's something necessarily specific to the project. It could easily be extracted out into a more generic form and as a separate gem (as you've pointed out from including WickedPDF).

**Comment by jamesst20** [comment]
> First I think it's best to understand exactly what those methods are actually doing, and subsequently what benefit they bring.
> 
> As far as I can tell they're either downloading or fetching from local asset mechanisms with specified asset, then injecting it into the response. Does that sound about right?
> 
> If that is the case, I'm not seeing a whole heap of benefits here. It also doesn't feel like it's something necessarily specific to the project. It could easily be extracted out into a more generic form and as a separate gem (as you've pointed out from including WickedPDF).

I did not look specifically at how it was implemented but indeed it must kind of be injecting the CSS/JS inline in the HTML so that it can be loaded.

"I'm not seeing a whole heap of benefits here."

The benefit here would be the ability to include CSS/JS from Sprockets asset pipeline or webpacker.
Unless I am currently mistaken, this is not currently possible, is it ?

**Comment by abrom** [comment]
You absolutely can include CSS/JS/images etc from sprockets or webpacker!

If you're using the middleware this will just work out of the box. 

If you're rendering the HTML in the controller then passing that to Grover you'll need to ensure your HTML doesn't have relative paths. See https://github.com/Studiosity/grover/#relative-paths

The key here is that Grover (Chromium) needs to have the full path to be able to resolve the assets.

**Comment by james-em** [comment]
> TML in the controller then passing that to Grover you'll need to ensure your HTML doesn't have relative paths. See https://github.com/Studiosity/grover/#relative-paths
> 
> The key here is that Grover (Chromium) needs to have the full path to be able to resolve the assets

Can't seem to get assets loading with the middleware.

Middleware setup:
![Screen Shot 2021-08-25 at 10 49 04 AM](https://user-images.githubusercontent.com/63726983/130812950-a2fe60c1-fc12-45d7-88bf-95726bd0dbb5.png)
![Screen Shot 2021-08-25 at 10 49 09 AM](https://user-images.githubusercontent.com/63726983/130812970-d1f8a5f7-e7b3-4eb9-bccc-6390a772c708.png)

Without line 11 & 12 it's displaying like there is no CSS
![Screen Shot 2021-08-25 at 10 49 32 AM](https://user-images.githubusercontent.com/63726983/130813055-df294bc3-6961-4386-9c5a-3ea1df046f33.png)

**Comment by abrom** [comment]
What have you done to test this? Have you tried any [debugging](https://github.com/Studiosity/grover#debugging)? 

Does setting the [root_url](https://github.com/Studiosity/grover#root_url apply to you?

**Comment by james-em** [comment]
> What have you done to test this? Have you tried any [debugging](https://github.com/Studiosity/grover#debugging)?
> 
> Does setting the [root_url](https://github.com/Studiosity/grover#root_url apply to you?

I don't think it applies. I'm testing localy.

I also tried another way around:

```
      options = grover_pdf_defaults.merge(options) if respond_to?(:grover_pdf_defaults)
      body_html = render_to_string action_name
      body_html = Grover::HTMLPreprocessor.process body_html, 'http://localhost:3000/', 'http'
      pdf = Grover.new(body_html, options).to_pdf
      send_data(pdf, filename: "#{grover_pdf_filename}.pdf", type: "application/pdf", disposition: :inline)
```

I have did do some debugging, after `Grover::HTMLPreprocessor.process` in the generated HTML the <link attribute changes from

```
  <link rel="stylesheet" media="all" href="/packs/css/application-dedaf984.css" />
```
to 
```
  <link rel="stylesheet" media="all" href="http://localhost:3000/packs/css/application-dedaf984.css" />
```

I tested the url by hand and it does resolve to my CSS

**Comment by abrom** [comment]
What is actually happening? PDF rendering with no styles applied? Or timing out? If it's timing out, suggests you only have a single worker available. In that situation you'd need to boot your Rails server with at least 2 workers. Can you confirm what version of puppeteer you have installed? Can you confirm what version of grover you have installed ?

**Comment by abrom** [comment]
Ahh.. that explains it. There was a change in puppeteer 10.2.0 that broke the asset rendering. See #122

You can either revert puppeteer back to 10.1.0 or update grover to v1.0.3 ;)

**Comment by james-em** [comment]
> Ahh.. that explains it. There was a change in puppeteer 10.2.0 that broke the asset rendering. See #122
> 
> You can either revert puppeteer back to 10.1.0 or update grover to v1.0.3 ;)

Upgraded everything webpacker, grover, etc. and now it works.
Wow can't believe it never worked because I probably came in the timeframe where it was broken with puppeter update

**Comment by alaarab** [comment]
If it helps anyone, I created this helper for myself. I had the same issues as OP and wanted the helpers, although the maintainers of this gem chose not to :

module GroverHelper
  def grover_stylesheet_link_tag(*sources)
    stylesheet_contents = sources.collect do |source|
      source = add_extension(source, "css")
      "<style type='text/css'>#{read_asset(source)}</style>"
    end.join("\n")

    stylesheet_contents.html_safe
  end

  private
    def add_extension(filename, extension)
      filename.to_s.split(".").include?(extension) ? filename : "#{filename}.#{extension}"
    end

    def read_asset(source)
      asset = Rails.application.assets_manifest.assets["#{source}"]

      if asset
        File.read(Rails.root.join("public", "assets", asset))
      elsif Rails.application.assets
        # Fallback to asset pipeline if manifest is not present, such as in development
        asset = Rails.application.assets.find_asset(source)
        asset.to_s if asset
      else
        Rails.logger.warn "Asset not found: #{source}"
        ""
      end
    end
end



and in my pdf.htmlerb:



  <%= grover_stylesheet_link_tag "application" -%>
  <%= grover_stylesheet_link_tag "pdf" -%>
