### ISSUE TITLE
Background image does not work.

### ISSUE THREAD

**Issue by gilderlan** [Studiosity/grover#125]
I need to generate a simple pdf with a background image and get the base64 code.

My code:

```
Grover.configure do |config|
  config.options = {
    format: 'A4',
    timeout: 0,
    emulate_media: 'screen',
    launch_args: ['--no-sandbox', '--disable-setuid-sandbox'],
    print_background: true
  }
end

html = %Q{
  <html>
    <head>
      <meta charset='UTF-8'>
      <style>
        body {
          background-image: url(http://img.freepik.com/free-vector/white-abstract-background_23-2148810113.jpg);
          background-repeat-y: repeat-y;
          background-position: center center;
          background-attachment: fixed;
          background-size: 100%;
          min-height: 600px;
        }
      </style>
    </head>
    <body>
      <h1>Teste</h1>
    </body>
  </html>
}

pdf = Grover.new(html).to_pdf
Base64.encode64(pdf)
```

The resulting pdf does not have a background image.

![image](https://user-images.githubusercontent.com/227866/130517116-a81fa31a-84ff-4e7a-bbe9-822d23194142.png)

**Comment by abrom** [comment]
Have you tried telling the browser to force printing the background? ie [-webkit-print-color-adjust](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-print-color-adjust)
```
@media print {
  -webkit-print-color-adjust: exact;
}
```

**Comment by abrom** [comment]
Oops.. i see you've set your media emulation to `screen`. You should be able to just add this (without the media tag) to your body style definition

**Comment by gilderlan** [comment]
I tried some suggestions, nothing works. Removing the emulate media option, adding media print style ...

**Comment by abrom** [comment]
Have you tried enabling the `raise_on_request_failure: true` option? 

Have you tried any debugging? https://github.com/Studiosity/grover#debugging
