### ISSUE TITLE
How to avoid locking up in development environment when the target HTML issues requests to the application itself

### ISSUE THREAD

**Issue by feliperaul** [Studiosity/grover#129]
I wish to render a view as a PDF, and what triggers the PDF generation is a 'generate pdf' POST request after a user clicks a button. Nothing fancy there (controller code is bellow). 

The target view is highly dynamic and uses React. When the React app loads, it makes HTTP requests to the application itself to load some JSON from the backend. 

These requests, however, always hang until timing out.

After a long debugguing session, I stumbled upon this: https://github.com/puma/puma/issues/2352

As per that issue, when a request is made and, before it finishes, it itself issues a request that hits the Rails application itself (which is the case here, because puppeteer will issue that JSON request during the request lifecycle that initiated it), it will lock up until timeout.

One way I managed to partially solve it was using `ActiveSupport::Dependencies.interlock.permit_concurrent_loads` suggested in that issue:

```rb
    html = render_to_string({ template: 'controller_name/action_name', layout: 'application', assigns: { ivar: SomeModel.last } })
    html = Grover::HTMLPreprocessor.process html, 'http://localhost:3000/', 'http'
    pdf = nil
    ActiveSupport::Dependencies.interlock.permit_concurrent_loads do
      pdf = Grover.new(
        html,
        format: 'A4',
        display_url: "http://localhost:3000",
        # debug: {
        #   headless: false,  
        #   devtools: true   
        # }
      ).to_pdf
    end
    send_data(pdf, disposition: 'inline', filename: "Show_ID_#{params[:id]}", type: 'application/pdf')
```

Not only that, but I'm also facing timeouts like this for assets requests, like fonts; however, they generally occur only after the first request after starting the dev server, and subsequent ones go just fine. 

So, I'm first posting this here to help any future Googlers, because I couldn't find anything in the issues.

At the same time, I wanted to know if I'm doing anything wrong to be the only one hit by this issue in development; if not, I can issue a pull request so we can enhance the docs about this (not so edge?) case.

**Comment by abrom** [comment]
That's not an issue I've seen before.

If your server only allows for one request at a time that is the behaviour I would expect. Puma will normally create somewhere between 5 and 16 worker threads by default, so unless you're expressly limiting that it should just work.

Your code example suggests that there is some thread locking going on.. you could always try increase the number of workers processes to get around any thread locking. ie add `workers 2` or similar to your config/puma.rb see https://github.com/puma/puma#clustered-mode

Happy to accept an update to the README 👍

**Comment by feliperaul** [comment]
@abrom I also just want to say thank you about this gem. Not only it's immensely useful, but the patterns you've used here have taught me a lot about how to effectively communicate between ruby and a node process. Just brilliant.

**Comment by abrom** [comment]
Not a problem, although I can't take the credit for that.. I drew great inspiration from https://github.com/Shopify/schmooze

Did increasing the worker (process) count work for you?

**Comment by feliperaul** [comment]
The problem only happens in development, where `puma.rb` defaults to 1 worker, with 5 threads.

Increasing it to 2 workers didn't solve the issue, and it's not easy to work with pry in a multi-worker environment.

I'm closing the issue until I have more information to share; right now, I have a timeout on every first request after I change any ruby code; after the second request, everything works fine. It's very weird, and even that is happening at random, I will come back when I have pinpointed the issue.
