### ISSUE TITLE
Images not rendering in PDF

### ISSUE THREAD

**Issue by raghavmalawat** [Studiosity/grover#130]
Using  rails (6.1.4)
Using  grover (1.0.5)
Using  puppeteer: "^10.0.0"

- Images are not rendering in the pdf's. Tried using the rails asset pipeline and even using html "img" tags providing relative paths as src
-  Executed `rake assets:precompile RAILS_ENV=development` too

1. <%= 
     image_tag(
      "#{Rails.root}/app/assets/images/xxxx.png",
      alt: "Alternate Text",
      class: "xxxx-image"
    )
  %>

2. <%= 
     image_tag(
      "xxxx.png",
      alt: "Alternate Text",
      class: "xxxx-image"
    )
  %>

3. `<img src="./../../assets/images/xxxx.png" alt="Alternate Text" class="xxxx-image">`

Above 3 are the variations we tried, the alternate message along with css specified in the image class gets rendered

NB: On debugging the intermediary html generated seems good (has the absolute path to the images in the local machine)

Images get displayed like below
![Screenshot 2021-10-05 at 12 06 51 PM](https://user-images.githubusercontent.com/30802908/135972488-4a33b788-0ac3-40c2-a413-0c96b1513970.png)

**Comment by raghavmalawat** [comment]
On digging further we found that, Puppeteer doesn't allow loading local resources hence images aren’t getting rendered, we tried uploading images to cloud and see it getting rendered

[https://github.com/puppeteer/puppeteer/issues/1643](https://github.com/puppeteer/puppeteer/issues/1643)

Closing this ticket

**Comment by raghavmalawat** [comment]
This helped us @abrom, thanks. Moving ahead with Grover 🙂

**Comment by devsheva** [comment]
The base64 trick seems the best option so far, it's working like a charm

**Comment by trv1** [comment]
Thank you so much @abrom. Only decision with base64 works for me. The docs must have this info!
