### ISSUE TITLE
Adding footer with page numbers

### ISSUE THREAD

**Issue by BigMcLargeHuge** [Studiosity/grover#136]
Hi there,

I seem to be unable to add page numbers to the document that I'm using Grover to export.  I've referenced and largely grabbed the code from [issue 72](https://github.com/Studiosity/grover/issues/72)

My Grover options are as follows:

    Grover.configure do |config|
      config.options = {
          format: 'Letter',
          print_background: true,
          display_header_footer: true,
          footer_template: "<div class='text right'><span class='pageNumber'></span>/<span class='totalPages'></span></div>",
          margin: {
              top: '0px',
              bottom: '0px'
          },
          viewport: {
              width: 2550, # Letter in pixels at 300 DPI
              height: 3300
          },
          prefer_css_page_size: true,
          emulate_media: 'screen',
          cache: false,
          timeout: 0, # Timeout in ms. A value of `0` means 'no timeout'

      }
    end

The footer IS being inserted, as I can see the slash in between the two spans in the `footer_template`.  What doesn't appear to be working are the classes `pageNumber` and `totalPages`, as neither number is being displayed on either side of the slash.  Please let me know if there's anything else I can provide.

**Comment by abrom** [comment]
You've set the bottom margin to `0px` giving the footer nowhere to render. Increase that up a smidge and you'll be able to see it.
