### ISSUE TITLE
Suggestion: allow using puppeteer-core package

### ISSUE THREAD

**Issue by cernyjakub** [Studiosity/grover#141]
Hello! I am trying to create a sane way to deploy a Rails app with grover to our production cluster. Our servers have Chromium installed so I would like to skip Chromium download during puppeteer install and just specify path to Chromium in the config (which works fine).

To skip download, I can:

- use `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD` env variable
- use `puppeteer-core` package, as noted on https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#puppeteer-vs-puppeteer-core

I would prefer to go with `puppeteer-core` (which is recommended way) so I don't have to introduce ENV variable mechanism for yarn during the deploy process. All works fine. The only missing piece is that `processor.js` hardcodes `puppeteer` package name to load. Would it be possible to also try to load `puppeteer-core`? It is the only difference... all works fine, if I patch the `processor.js` on line 5 manually.

Thanks for this cool library!

**Comment by abrom** [comment]
Seems like a reasonable idea. I've created a branch that *should* do this:

https://github.com/Studiosity/grover/compare/try-load-puppeteer-core

I've added a basic test for loading the core package, however I haven't modified the test to actually install a separate Chrome/Firefox version so it isn't testing a "successful" use of Grover/puppeteer-core..

If you can test it out and see that it works as you'd expect that would be appreciated. I've also updated the README with some instructions however I haven't actually tested them myself. If you can validate that's all you need to change that would also be appreciated.

**Comment by cernyjakub** [comment]
OK, cool - I will test later today. In the meantime, I have also found a pure "yarn based" solution using yarn/npm _aliasing_ feature  (which I was not aware of):

you simply add puppeteer using: `yarn add puppeteer@npm:puppeteer-core`

In this case, loading `puppeteer` module succeeds... just using packaging magic ;)

I don't know which solution is better, maybe support for plain `puppeteer-core` would be easier. But probably adding this trick to README would be fine too...

**Comment by abrom** [comment]
This is supported as of [v1.1.7](https://rubygems.org/gems/grover/versions/1.1.7)
