### ISSUE TITLE
How to use wait_until with manually uploaded images?

### ISSUE THREAD

**Issue by daryld212** [Studiosity/grover#142]
I currently have an issue where certain images are not loading. I plan to shift to a different image server which should solve the issue, but until then can someone confirm that I'm using the best settings for "wait_until" correctly?

![Screen Shot 2021-11-20 at 16 42 05](https://user-images.githubusercontent.com/90428992/142745133-aedc2d1f-8ad6-4cf4-88f6-11e43ad92f0f.png)

Currently have this in my Grover.rb initializer file:
```
user_agent: "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0",
wait_until: ["load", "domcontentloaded", "networkidle0", "networkidle2"],`
```

**Comment by abrom** [comment]
looks to me more like a path issue (404) in loading the image. Suggest checking out the debugging section in the README when you can set the browser to show itself (`debug: { headless: false }`) 

that or you could set `raise_on_request_failure: true` which would error out when (if) there is a path load issue.

If neither of the above help, you could always use the `wait_for_function` and use JS to check that the image has loaded (but I highly doubt this would help.. it very much looks like the image has attempted to load.. and failed!)
