### ISSUE TITLE
Setting locale on puppeteer launch

### ISSUE THREAD

**Issue by henryaj** [Studiosity/grover#146]
I'm having trouble figuring out how to set the system locale to get dates and times rendered appropriately in generated PDFs. I'm in the UK, and the date format here is DD/MM/YYYY, but I only get US dates in generated PDFs.

Have tried setting the following in the Grover initialiser:

```
{
  timezone: "Europe/London",
  launch_args: ["--lang=en_GB"],
  extra_http_headers: {"Accept-Language": "en_GB"}
}
```

but to no avail. Any ideas how I should proceed?

**Comment by abrom** [comment]
The first question i think needs answering is, are you sure the page you're trying to render does follow the locale specified ?  There is of course no guarantee that this would be the case. Are you trying to convert a URL, or raw HTML? Do you know if the date is being rendered server side? or client side? 

One *possible* issue is that you appear to be using the ISO language format and there *may* be unexpected results from a server that is expecting RFC5646 language codes. ie `en_GB` vs `en-GB`. I know Chromium doesn't care, but you haven't provided much in the way of other details, so... 

I can tell you that with the latest Puppeteer (v12.0.1) the above args you provided work as expected for me

The `Accept-Language` header is going to be passed through to the remote server and used to decide how things should be rendered server side. And the launch arg `--lang=...` will tell the browser how it's supposed to behave client side.

For example:
```
Grover.new(
  'http://www.google.com',
  extra_http_headers: { 'Accept-Language' => 'es-AR' },
  launch_args: ['--lang=en-GB']
).to_pdf('/tmp/foo.pdf')
```
will render the page in Spanish

and..

```
Grover.new(
  <<~HTML,
    <html>
      <body>
        <div id="foo">Foo</div>
        <script>document.getElementById("foo").innerText = new Date().toLocaleDateString()</script>
      </body>
    </html>
  HTML
  extra_http_headers: { 'Accept-Language' => 'en-US' },
  launch_args: ['--lang=en_GB']
).to_pdf('/tmp/foo.pdf')
```
will render the date in `en_GB` format. 

HTH

**Comment by henryaj** [comment]
Thanks for the quick reply! For context, this is a date in a form that's appearing within a standard HTML5 datepicker element. Locally it shows in the UK format; when running on Heroku the PDFs come back with the US formatted date.

When I call:

```ruby
Grover.new(html,
  {
    print_background: true,
    extra_http_headers: {"Accept-Language" => "en-GB"},
    launch_args: ["--lang=en_GB"]
  }).to_pdf
```

I still see dates inside datepickers rendered in the US style. Is there anything else I ought to be trying here? I've seen some threads elsewhere suggesting chromium isn't respecting the `--lang` flag and that the `LANG` env var works; not sure if that's something Grover supports.

Any pointers would be much appreciated.

**Comment by abrom** [comment]
Right... 

Good news.. I can replicate your issue now. Bad news.. I can't figure out how to fix it! I suspect this is either a feature (or a bug) of Puppeteer/Chromium. 

According to the Puppeteer API docs the current "correct" way to set the language (client/render side) is to overload the navigator.language/languages methods. See https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pageevaluateonnewdocumentpagefunction-args

I've tried that, as well as passing through the `LANG` env and the launch args etc.. On that, note that Grover will pass through any system envs to the node processor, and the node processor will pass any of those on to Chromium. So simply setting `LANG` when starting your Ruby process would achieve this - although wouldn't solve your issue.

In the end I believe all of the above are all "working" and achieving the same result (overloading the navigator language) but it looks like Chromium is not using that for the render format for the date input! It would seem that it is using a different system setting for date inputs, however I couldn't tell you what that is! I think your best bet would be to raise it up the line (ie check with the Puppeteer team if they have any ideas, and if that fails check with Chromium).

Another thought, have you tried using Firefox with Grover? I haven't tested this use-case, but it may be that its render engine will handle this differently?

**Comment by henryaj** [comment]
Thank you *so* much for your help with with @abrom - in the end I moved to a custom datepicker element that displays the date unambiguously. I might still raise it with the puppeteer/chromium team and will link here if I do.

(This all did provide me with a chance to refactor a lot of the PDF generation code in my app, so not a wasted effort!)
