### ISSUE TITLE
Timeout not being respected

### ISSUE THREAD

**Issue by taggartbg** [Studiosity/grover#150]
I am trying to render a PDF of a React application using `wait_for_function`.  I have the timeout, request_timeout, and wait_for_function_options timeout all set to 0, but it still renders after 30 seconds.  I have also tried bumping them up to very large numbers.

I create my Grover instance with:
```
content = Grover.new(url, grover_options)
content.to_pdf
```
and my `grover_options` are:
```
    {
      margin: {
        top: options.margin_top,
        bottom: options.margin_bottom,
        left: options.margin_left,
        right: options.margin_right
      },
      print_background: true,
      style_tag_options: {
        html: '-webkit-print-color-adjust: exact;'
      },
      wait_for_function: 'window.printReady === true',
      wait_for_function_options: {
        timeout: 0
      },
      display_header_footer: true,
      header_template: header_template,
      footer_template: footer_template
    }
  ```
  my `grover.rb` initialization is:
  ```
  Grover.configure do |config|
  config.options = {
    format: 'Letter',
    launch_args: [
      '--no-sandbox'
    ],
    timeout: 0,
    request_timeout: 0
  }
end
```

I have tried putting `timeout`, `request_timeout`, and `wait_for_function_options` in both the initialization and the grover_options, but I can't get anything to render if it is above 30000ms.

If it is under 30000ms it loads fine.  Here is my test code:
```
function mountTest(target, clientId, page) {
  setTimeout(() => {
    ReactDOM.render(<div>test</div>, target, () => {window.printReady = true})
  }, 31000)
}
```

I saw this (https://github.com/Studiosity/grover/issues/143) and I am on Grover 1.1.1 and Puppeteer 12.0.1

Thanks for any guidance!

**Comment by abrom** [comment]
Hmm I can't replicate your issue. I removed some of the bits that would not appear to be specific to your setup, but that would not affect the outcome of the test:

```bash
$ npm list
grover@1.1.1
└── puppeteer@12.0.1
```

```ruby
> Grover.configure do |config|
config.options = {
  format: 'Letter',
  launch_args: [
    '--no-sandbox'
  ],
  timeout: 0,
  request_timeout: 0
}
end

grover_options = {
      print_background: true,   
      style_tag_options: {         
        html: '-webkit-print-color-adjust: exact;'
      },                                          
      wait_for_function: 'window.printReady === true',
      wait_for_function_options: {
        timeout: 0
      }
}

html = <<~HTML
  <html><body>
    <div id="foo"></div>
    <script>
      setTimeout(
        function() { document.getElementById("foo").innerText = "bar"; window.printReady = true; },
      40000)
    </script>
  </body></html>
HTML

> start_time = Time.now; Grover.new(html, grover_options).to_pdf('/tmp/foo.pdf'); "Time taken: #{Time.now - start_time}" 
 => "Time taken: 40.628708"
```

I used 40 seconds to make sure it was super clear of the timeout not coming into play. The PDF generated contains the word "bar". Seems like maybe you've got something else going on here?

**Comment by alagos** [comment]
Same issue here. 
I'm using Grover 1.1.5, last puppeteer 21.3.6 and the html file I'm using is about 3MB, with no `setTimeout` and after 30 seconds I get:
```
Grover::JavaScript::TimeoutError: waiting for Page.printToPDF failed: timeout 30000ms exceeded
```
I added a fixed timeout with
```
timeout: 1_800_000, # 30 minutes
```
but nothing really changed. In any case, this seems to be an issue [with puppeteer](https://github.com/puppeteer/puppeteer/issues/8356) more than Grover. 
I'll try to reproduce it only using node and I'll report it to the puppeteer team instead.
