### ISSUE TITLE
Cannot access locals in pdf template

### ISSUE THREAD

**Issue by mohd-anas-ansari** [Studiosity/grover#154]
I am trying to generate PDF using Grover in my ActionMailer.
Here's my `invoice` action in mailer`invoice_mailer`: 
```rb
def invoice
    @invoice = params[:invoice]
    recipients = params[:recipients]
    subject = params[:subject]
    @message = params[:message]

    # Generating PDF from template invoices/pdf

    controller = ActionController::Base.new
    html = controller.render_to_string(
      template: "invoices/pdf",
      layout: "layouts/pdf",
      locals: {
        :invoice => @invoice
      })

    style_tag_options = [
      { content: "h1{background-color: red}" }
    ]

    pdf = Grover.new(html, style_tag_options: style_tag_options).to_pdf

    attachments["invoice_#{@invoice.id}.pdf"] = pdf

    mail(to: recipients, subject:)
  end
```

`views/invoices/pdf.html.erb`:
```rb
<h1><%=invoice["id"]%></h1>
```

But turns out I cannot pass locals to PDF generation in Mailer. 

It shows:
```
NoMethodError
undefined method `[]' for nil:NilClass
```
Passing locals in `invoice_controller` works fine. I was able to download the PDF too.

Does Grover support locals in Mailer? 
Is there any way I can access locals in PDF generated in Mailer?
Or is it some bug Grover?

**Comment by abrom** [comment]
Not sure I see how this is a Grover issue?? It sounds like you either have an issue rendering a template to HTML, or it's your assignment of the `attachments` variable. You haven't provided a call stack so I can only guess.

**Comment by mohd-anas-ansari** [comment]
I understand. Thank you for the clarification. Closing the issue.
