### ISSUE TITLE
Grover not displaying any css in prod. Works fine in dev

### ISSUE THREAD

**Issue by spacerobotTR** [Studiosity/grover#155]
Just getting this all set up with deploy via capistrano. The pdf renders in production, but it is not applying any tailwind styles. In development everything renders correct. Any thoughts on why? Here is how I export:

```
def export_to_pdf

    html = render_to_string(action: :show, layout: 'pdf', formats: [:html], locals: { :@invoice => @invoice })
    r = Grover::HTMLPreprocessor.process(html, 'http://localhost:3000/', 'http')

    respond_to do |format|
      format.html { render html: html }
      format.pdf do
        render_pdf(r, filename: @invoice.pdf_file_name)
      end
    end
end
```

**Comment by spacerobotTR** [comment]
As a work around I included the link to the tailwind cdn in the head of my pdf layout. It is working now. Not sure how to set the path of the stylesheets for grover with capistrano deploy.

**Comment by abrom** [comment]
Visiting that page and setting the CSS media type to print (as Grover does) I get what appears to be the same rendered output as captured in the PDF. I would suggest adding `emulate_media: 'screen'` to the options. 

See https://github.com/Studiosity/grover#configuration

Alternatively you could include `print` (or `all`) in the media tag as specified in your main stylesheet:
```
<link rel="stylesheet" media="screen" href="https://assets.spikeatschool.co.nz/vite/assets/online_newsletter.be3d1035.css" data-turbo-track="reload">
```
Note I see there are two "online_newsletter" stylesheets. The other one does specify `media="all"` but it doesn't appear to have much in it (some `trix-editor` styles).

HTH

**Comment by brendon** [comment]
Ah of course! I was thinking about it on the way to work and figured it must have been something to do with the `media` attribute. I guess because the CSS is dynamically added to the page in development due to HMR it sidesteps the media specification :) Grateful for your help :D
