### ISSUE TITLE
gap css property alters PDF printing

### ISSUE THREAD

**Issue by maxence33** [Studiosity/grover#158]
First thanks a lot for this fantastic gem. It is just great to be able to print a pdf with modern CSS.

Though I have come upon a weird behavior. When using the css property `gap` the printing of the pdf file is disrupted: only partial information is displayed, and final PDF counts more than 29k pages. 
Removing the `gap` property from my styling fixes the problem. The HTML in both Firefox and Chrome do work fine with the `gap` property. 

Edit: seems like `column-gap` works fine, but `row-gap` triggers the previously detailed behavior.

**Comment by abrom** [comment]
hi @maxence33

I would suggest looking at the print page for the rendered HTML in Chrome (closest analog to Chromium). That will likely explain any layout issues and possibly help you with debugging your styling issues further. You can also use the browser inspector to emulate a specific media type ie `print`! (See `Rendering` tab and the `Emulate CSS media type` setting)

The page is rendered by Chromium (by default) and any layout issues would need to be solved with that in mind. Grover simply calls out to the Puppeteer node library which drives the browser! 

Another option (if using the `print` media type is a problem) would be to specifically tell Grover to pass through a different media type (eg `screen`). You can do this either when [creating the Grover instance](https://github.com/Studiosity/grover#usage) with `emulate_media: 'screen'` option, or this can be done "globally" using [Grover.configure](https://github.com/Studiosity/grover#configuration), or you could pass the configuration through in the HTML [via a meta tag](https://github.com/Studiosity/grover#usage) eg `<meta name="grover-emulate_media" content="screen">`

HTH

**Comment by maxence33** [comment]
Hi @abrom , 

Thanks a lot for your debugging tips. Hopefuly I only need `gap-column` to space elements horizontally. Though I have tried to debug `gap` and it still works fine with Firefox and Chrome. So the problem is probably with Chromium.
Even emulating screen still triggers the problem. 
I will close the ticket as it has nothing to do with Grover indeed. 

I will check the Chromium repo to see if something exists about the problem there. 
Thanks
