### ISSUE TITLE
Unable to run it on Heroku

### ISSUE THREAD

**Issue by pvaldesoiro** [Studiosity/grover#166]
Hello Grover team,

First of all, thank you for your work on this tool.

I have been trying to run Grover in a rails app to generate PDFs from HTML (not from views, but from standalone HTMLs). When I run it locally, it runs perfectly. But when I run it on the server (deployed to Heroku), it's impossible for me to make it work. It gives me a runtime error:
```
2022-11-13T22:43:47.411370+00:00 app[web.1]: Grover::JavaScript::Error (Could not find Chromium (rev. 1056772). This can occur if either

2022-11-13T22:43:47.411371+00:00 app[web.1]:  1. you did not perform an installation before running the script (e.g. `npm install`) or

2022-11-13T22:43:47.411374+00:00 app[web.1]:  2. your cache path is incorrectly configured (which is: /app/.cache/puppeteer).

2022-11-13T22:43:47.411374+00:00 app[web.1]: For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.):
```

Project stack:
- Grover 1.1.2
- Ruby 3.1.2
- Rails 6.1.7
- Node 18.12.1
- Puppeteer 19.2.2 (in package.json)

Buildpacks in order:
- heroku/nodejs
- https://buildpack-registry.s3.amazonaws.com/buildpacks/jontewks/puppeteer.tgz
- heroku/ruby

Environment variable:
- GROVER_NO_SANDBOX=true

My actions:
- I have tried to purge my Heroku cache as recommended in the [Puppeteer buildpack](https://elements.heroku.com/buildpacks/jontewks/puppeteer-heroku-buildpack).
- I have followed the requirement that was shown in a previous error of adding the Puppeteer dependency to my package.json (through yarn).
- I have purged cache again.
- I have tried several Node versions (16 and 18)
- I don't have any puppeteer configuration file, any javascript code, nor have I configured any cache path.

Thank you for your help.

**Comment by pvaldesoiro** [comment]
Okay, I found the problem. There was a [breaking change](https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer/CHANGELOG.md#1900-2022-10-14) in Puppeteer 19.0.0.

**I fixed it by downgrading to Puppeteer 18.2.1.**

I think it could be helpful for anybody that tries to use Grover to add a note at the [Readme.md](https://github.com/Studiosity/grover#readme) advising users to keep the Puppeteer version equal or under 18.2.1 (if they are going to use Heroku, at least) until something changes, be it in Grover or in Puppeteer.

**Comment by abrom** [comment]
Hi @pvaldesoiro

Can you check your Heroku instance to see where it was installing Chromium?? (ie `heroku ps:exec` to get a shell). Historically this was found in something like:
```
/app/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome
```
but presumably with puppeteer 19.x it would be in:
```
/app/.cache/puppeteer/...
```

Of course I'm assuming you believe the breaking change to be the install path change? If you do see that it is being install somewhere else you can override the default executable path for puppeteer using the `executable_path` option. 

Per the puppeteer docs you can specify where it should install things by creating a `.puppeteerrc.cjs` or `puppeteer.config.cjs` file in the root of your project. See https://pptr.dev/#configuration

**Comment by abrom** [comment]
FYI I just tried setting up a fresh Heroku instance to test this. I was able to replicate the same error you received. I found that creating a `.puppeteerrc.cjs` file in the root of the project with:
```
const {join} = require('path');

/**
 * @type {import("puppeteer").Configuration}
 */
module.exports = {
  cacheDirectory: join(__dirname, '.cache', 'puppeteer'),
};
```

I found puppeteer v19.x works just fine! 

Interestingly setting the cache dir using an ENV var didn't work?!

**Comment by pvaldesoiro** [comment]
Hello @abrom ,

I commented on the PR. In my project, I will upgrade puppeteer to the most recent version, and add the `.puppeteerrc.cjs` file with the configuration that you shared.

Thank you for your help.
