### ISSUE TITLE
Is there any way to emulate timezone in puppeteer on a per request basis? I have tried the following config but to no avail

### ISSUE THREAD

**Issue by chirag-shipmnts** [Studiosity/grover#168]
`        pdf_data = Grover.new(html, {timezone: 'Australia/Sydney'}).to_pdf
`

**Comment by abrom** [comment]
Can you elaborate on what "no avail" means? What did you expect? What did you actually get? What JS API are you trying to use? How are you trying to use that API? What versions of the gem/puppeteer have you got installed?

You can see in the tests that the feature changes the timezone offset just fine (for Puppeteer v2.0+) ie `Date().getTimezoneOffset()`

https://github.com/Studiosity/grover/blob/main/spec/grover/processor_spec.rb#L432-L460
