### ISSUE TITLE
Using Grover with Firefox

### ISSUE THREAD

**Issue by railsoid** [Studiosity/grover#173]
First of all, I'd like to thank everyone who's been working on this project, it really makes it so convenient and simple to generate PDF - great job!

I've recently ran into an issue with a table that has rowspan specified, for some reason Chrome/Chromium are rendering this table with multiple page breaks where rowspan is specified. It's not an issue with either Grover or Puppeeter as I get the same result if I print that html through Chrome. However, it's been printed as expected in Firefox therefore my initial intention is to switch to using that browser (knowing it's supported by Puppeeter). This is where I've got stuck, as Grover does provide some configuration options via initializer, but it does not respect product: 'firefox' option as it goes to args, not to the root of launch params. I have modified this code in grover/js/processor.cjs to include this option:

```
    const launchParams = {
      product: 'firefox',
      args: process.env.GROVER_NO_SANDBOX === 'true' ? ['--no-sandbox', '--disable-setuid-sandbox'] : []
    };
```

However, I'm getting the following exception:
`"#<Grover::JavaScript::ProtocolError: Protocol error (Network.setExtraHTTPHeaders): Network.setExtraHTTPHeaders RemoteAgentError@chrome://remote/content/cdp/Error.sys.mjs:20:5\nUnknownMethodError@chrome://remote/content/cdp/Error.sys.mjs:103:7\nexecute@chrome://remote/content/cdp/domains/DomainCache.sys.mjs:92:13\nreceiveMessage@chrome://remote/content/cdp/sessions/ContentProcessSession.sys.mjs:79:45\n>"`

Looking through this problem I've found out there is unresolved issue with this method in Firefox:
https://bugzilla.mozilla.org/show_bug.cgi?id=1549462

And if I comment out this part of the code in processor.cjs to not set any http headers (at least for testing purposes)

```
    // Add extra HTTP headers (if provided)
    // const extraHTTPHeaders = options.extraHTTPHeaders; delete options.extraHTTPHeaders;
    // if (extraHTTPHeaders !== undefined) {
    //   await page.setExtraHTTPHeaders(extraHTTPHeaders);
    // }
```

I am getting the next issue:
`"#<Grover::JavaScript::ProtocolError: Protocol error (Fetch.enable): Fetch.enable RemoteAgentError@chrome://remote/content/cdp/Error.sys.mjs:20:5\nUnknownMethodError@chrome://remote/content/cdp/Error.sys.mjs:103:7\nexecute@chrome://remote/content/cdp/domains/DomainCache.sys.mjs:92:13\nreceiveMessage@chrome://remote/content/cdp/sessions/ContentProcessSession.sys.mjs:79:45\n>"`

Which looks to be related to another unresolved mozilla issue with Fetch.enable
https://bugzilla.mozilla.org/show_bug.cgi?id=1587857

I do understand it's not related to the Grover itself and this seems more like a forum topic rather than github issue, but I'm wondering whether anyone was able to make it work with Firefox?

**Comment by abrom** [comment]
hey @railsoid 

Good question.. but in short it looks like although Puppeteer supports Firefox, Firefox doesn't support all of the things Puppeteer needs. In this case it's the `Fetch.enable` function as used by the puppeteer `Page#setRequestInterception` function used by Grover to inject the requested content into the browser. AFAICT the response from the Firefox team was something to the effect "who would need that?!" 😬  The issue is 3+ years old so a positive resolution seems.. unlikely (at least in the near term). Best option would likely be to continue to petition the Firefox team to add support.
