### ISSUE TITLE
Ruby 3.2 support

### ISSUE THREAD

**Issue by breisig** [Studiosity/grover#174]
When attempting to using Grover 1.1.2 under Ruby 3.2.0, it says

```
grover-1.1.2 requires ruby version < 3.2.0, >= 2.6.0, which is incompatible with the current version, ruby 3.2.0p0

```

We need support for Ruby 3.2

**Comment by abrom** [comment]
I've released Ruby 3.2.x grover support in [v1.1.3](https://rubygems.org/gems/grover/versions/1.1.3)
