### ISSUE TITLE
Trying to user Grover with Arabic text 

### ISSUE THREAD

**Issue by RimonAdel** [Studiosity/grover#180]
Hello all, thank you for this amazing gem. 

I am trying to generate image with Arabic text from html template. the English Text looks fine, but I can't make the Arabic work. 
I thought the problem might be in puppeteer or the fonts. But when i used url for a website that have Arabic text the Image was fine.
` 

    ac = ApplicationController.renderer.new()
    
    html = ac.render_to_string("shared/certificates/certificate", :locals => { some data }, encoding: "UTF-8")
    
    puts html
    
    grover = Grover.new(html, format: "png")
    
    png = grover.to_png
    
    send_data(png, type: "image/png", disposition: "inline")
    
`

![Screenshot 2023-02-22 at 12 06 50 PM](https://user-images.githubusercontent.com/35565654/220588564-e20b128d-bfb6-42fe-962d-a22257f043de.png)

**Comment by RimonAdel** [comment]
the problem was from turbo-rails. I solved it with adding "layout: false" to "render_to_string" method.

**Comment by abrom** [comment]
Hmm interesting problem. Your solution would suggest that something was being included in your layout that was messing with the fonts?? Go with what works, of course.. but you could potentially also try overload the font for the page and bump the specificity of the CSS to ensure it overrides what ever styles the layout was including!

There are also options for enabling debugging of the process, as well as how to disable the "headless" mode so you can see the browser before it renders to pdf/image. The details of how to do this are listed in the README :)
