### ISSUE TITLE
Cannot find module 'puppeteer-core/internal/puppeteer-core.js

### ISSUE THREAD

**Issue by nicks6853** [Studiosity/grover#182]
Hello,

I am attempting to use Grover in a Rails project but am encountering this error.

Cannot find module 'puppeteer-core/internal/puppeteer-core.js'. You need to add it to 'project-folder/package.json' and run 'npm install'

I am using the following:

- grover 1.1.4
- puppeteer 19.7.2
- ruby 2.7.2
- Rails 7.0.4
- Node 18.14.2 (also used 16.18.0 at some point but that didn't work either)
- npm 9.5.0

Here is my package.json

```json
{
  "name": "project",
  "version": "1.0.0",
  "description": "This README would normally document whatever steps are necessary to get the application up and running.",
  "main": "index.js",
  "directories": {
    "lib": "lib",
    "test": "test"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "puppeteer": "^19.7.2"
  }
}

```

Here is grover from my Gemfile:
```ruby
gem "grover", "1.1.4"
```

I use Grover in the following way:

```ruby
format.pdf do
  html = render_to_string(
    "pdf/information_sheet",
    layout: false,
    formats: [:html],
    # disable_smart_shrinking: true,
    # viewport_size: "1280x1024",
  )
  pdf = Grover.new(
    html,
    format: "A4",
    print_background: true,
    raise_on_request_failure: true,
    debug: true,
    launch_args: ["--ignore-certificate-errors"],
  ).to_pdf
  send_data(pdf, filename: "InformationSheet-#{DateTime.now.strftime("%F-%T")}.pdf", type: "application/pdf", disposition: :inline)
end
```

I tried installing puppeteer-core and that didn't work.
The only way I was able to get it to run was by using 18.1 which is not supported anymore.

Does anyone have any input on this? Seems like any version of puppeteer (18.2.x and higher) throws this error.

**Comment by abrom** [comment]
Hmm interesting problem. The only thing that stands out to me is the path in the error message. Specifically
```
project-folder/package.json
```
"normally" that would just be `package.json` (using `Dir.pwd`) but if it is including some other path in there, and you're not specifically defining the root location of the package.json file with the `root_path` option, then it suggests there's something funny about how your environment is setup?! I also can't explain why reverting to an earlier Puppeteer version would fix it for you. Can you tell me what `Dir.pwd` is (relative to your project root)? Can you try specifying the `root_path` option with the path of your `package.json` file?

**Comment by CeceliaYu** [comment]
i'm using jasmine + grunt and getting similar error:
```
 Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './internal/puppeteer-core.js' is not defined by "exports" in <<node_module_path>>/grunt-contrib-jasmine/node_modules/puppeteer-core/package.json
```

**Comment by abrom** [comment]
Doesn't appear to be any movement on this. Feel free to re-open if you need to/can reply to my questions 😄
