### ISSUE TITLE
Setting PDF Title & Language to create Accessible PDFs 

### ISSUE THREAD

**Issue by MazOneTwoOne** [Studiosity/grover#190]
I'm having trouble figuring out how to set the PDF metadata in particular setting the PDF title & PDF language. 

By not setting these, my PDF fails some PDF/UA standards. 

Have tried setting the following in the Grover initialiser:

```
    grover_options = {
      timezone: "Europe/London",
      vision_deficiency: 'deuteranopia',
      emulate_media: "print",
      launch_args: ["--font-render-hinting=medium", "--lang=en-GB", "--no-sandbox"],
      extra_http_headers: { "Accept-Language": "en_GB" },
    }

    pdf = Grover.new(html, **grover_options).to_pdf
```

Any help much appreciated.

**Comment by abrom** [comment]
That's a good question @MazOneTwoOne. 

I had a look into the options for doing this in Puppeteer (the library driving Chromium) but the maintainers essentially so, no.. not until Chromium supports it. There are some tickets on the Chromium project to add support but there doesn't appear to have been much movement on them, so I wouldn't hold you breath waiting for support to be added. The recommendation then was to use an external tool such as `exiftool` to modify the metadata once the PDF has been created.

HTH

**Comment by MazOneTwoOne** [comment]
Thanks @abrom

**Comment by patrick-laa** [comment]
FWIW, frustratingly, `exiftool` isn't capable of setting the language in the PDF catalog, which is where it needs to be to meet accessibility requirements. `exiftool test.pdf -Language:PDF=en-GB` yields `Warning: Sorry, Language:PDF doesn't exist or isn't writable`. Likewise `pdftk`'s `update_info` only writes the info dictionary, not the PDF catalog. If I find a tool that allows for editing the catalog I'll update here.

**Comment by patrick-laa** [comment]
OK, for editing the "catalog" metadata [hexapdf](https://hexapdf.gettalong.org/) seems to work:

```ruby
doc = HexaPDF::Document.open("path/to/grover-output.pdf")
doc.catalog.value[:Lang] = "en-GB"
doc.write("path/to/final-file.pdf")
```
