### ISSUE TITLE
Stylesheet is not rendered in production environment

### ISSUE THREAD

**Issue by BrycePPM** [Studiosity/grover#192]
Hello, I am using grover to generate a haml webpage to a pdf file. It is not rendering stylesheet in prod environment but in dev it works well. I can't find any info related to this case in documentation and others' issues. 

This is the method: 
````ruby
    def download
        # initialise response
        @feedback_request = FeedbackRequest.find(params[:id])
        @feedback_responses = FeedbackResponse.where(feedback_request_id: @feedback_request.id)
        
        html = render_to_string(layout: 'application', template: 'feedback_requests/report4download')
 
        absolute_html = Grover::HTMLPreprocessor.process html, "#{ request.base_url + '/' }", "#{ request.scheme }"
        grover = Grover.new(absolute_html, format: 'A3', print_background: true)

        pdf = grover.to_pdf
        send_data pdf, filename: 'report.pdf', type: 'application/pdf', disposition: 'attachment'
    end
````
Any help would really be appreciated. 
Thank you!

**Comment by abrom** [comment]
hi @BrycePPM 

I would suggest starting by enabling the `raise_on_request_failure` option. Per the README:
```
The raise_on_request_failure option, when enabled, will raise a Grover::JavaScript::RequestFailedError if the initial content request or any subsequent asset request returns a bad response or times out.
```
That would at least tell you if there are any broken URLs.

Or, you could add some debug logging to your controller action to see what the `absolute_html` actually is. It'd be verbose of course, but you could dump that to a file/files whilst testing.

Or, you could load up a console in your prod environment and try running the code in your controller to see what your HTML actually looks like. You can pass through the instance variables as such:
```
html = ApplicationController.renderer.render_to_string(
  layout: 'application',
  template: 'feedback_requests/report4download',
  locals: {
    '@feedback_request': FeedbackRequest.find(params[:id]),
    '@feedback_responses': FeedbackResponse.where(feedback_request_id: @feedback_request.id)
  }
)
absolute_html = Grover::HTMLPreprocessor.process html, '<your request base url>', '<your request scheme>'
puts absolute_html
```
Then you can check if the asset URLs actually work.. and that means making the request for that asset ON THE HOST that is trying to generate the PDF. That's where the request for the assets will be coming from!

Of course it may be that you are specifying a custom asset host (such as `config.action_controller.asset_host` in Rails). You haven't given up much in terms of how your system is configured (and there are a lot of ways to set that sort of stuff up to make use of CDN infrastructure etc!!). I can only guess so much :wink:

I would also check that you don't have some sort of URL re-writing going on between your public interface and the Rails backend that is messing around with your request base URL and scheme. For example using URL re-writing. If you are using some sort of URL re-writing, then that might be pointing to something that the host that is trying to render the PDF can't access.
