### ISSUE TITLE
`translate_relative_paths` misses the slash if it is not in the url

### ISSUE THREAD

**Issue by RasimKhusaenov** [Studiosity/grover#194]
When I call `Grover::HTMLPreprocessor.process` with a link that doesn't end with a slash (e.g. "localhost:3000" instead of "localhost:3000/") it translates "/image/some.png" to "localhost:3000image/some.png" instead of "localhost:3000/image/some.png".

https://github.com/Studiosity/grover/blob/v1.1.5/lib/grover/html_preprocessor.rb#L18-L21

**Comment by abrom** [comment]
Correct. Per the README example:
```
absolute_html = Grover::HTMLPreprocessor.process relative_html, 'http://my.server/', 'http'
```
the method is expecting a URI with, at a minimum, a path of `/`.

**Comment by RasimKhusaenov** [comment]
@abrom, WDYT of the idea of determining in the method itself whether a slash is worthwhile, and substituting inside the method depending on that? We store the url in an env variable and it would be more convenient to just substitute its value when calling the method instead of writing `Grover::HTMLPreprocessor.process(relative_html, project_url + '/', 'http')`.

**Comment by RasimKhusaenov** [comment]
@abrom, why can't we add a something like `root_url += '/' unless root_url.ends_with?('/')`?

**Comment by abrom** [comment]
It would be a breaking change that could be problematic for anyone expecting that behaviour.

An example scenario would be someone who had URL re-writing going on in their front-end/Load balancer. Something where they NEED to have the "root URI" not end in a slash. If there had been an option to opt in to the current behaviour then I'd say it'd be fine.... but there wasn't. It would be a breaking change.
