### ISSUE TITLE
Grover::Error (SyntaxError: Unexpected token '.')

### ISSUE THREAD

**Issue by diegodev9** [Studiosity/grover#196]
I have this error in production but not in development

**Comment by abrom** [comment]
Unless you can provide details of what your configuration looks like, how you're using the library and what the input looks like there isn't a lot that can be done.

**Comment by diegodev9** [comment]
Solved!!. It was a series of misconfigurations. I solved this by using debian 11 on my server (I was trying on debian 12) and adding the passenger gem... It worked for me.

**Comment by Laykou** [comment]
I'm having similiar issue `Grover::Error: SyntaxError: Unexpected token '??='` but only via web request.

When I run something like:

```
File.open('/path/to/a.pdf', 'wb') { |f| f.write(Grover.new(File.read('/path/to/a.html')).to_pdf) }
```

it works in console:
![image](https://github.com/Studiosity/grover/assets/2313005/858d2889-d23d-4d6f-bc3f-649bbe066f13)


but not when I run this exact line in controller (web request):
![image](https://github.com/Studiosity/grover/assets/2313005/2f4009db-b54e-46f2-a5b9-935dad8f12ce)

```
/Users/laykou/Projects/flowis/vendor/bundle/ruby/3.2.0/gems/grover-1.1.5/lib/grover/processor.rb:54:in `parse_package_error'
/Users/laykou/Projects/flowis/vendor/bundle/ruby/3.2.0/gems/grover-1.1.5/lib/grover/processor.rb:49:in `ensure_packages_are_initiated'
/Users/laykou/Projects/flowis/vendor/bundle/ruby/3.2.0/gems/grover-1.1.5/lib/grover/processor.rb:19:in `convert'
/Users/laykou/Projects/flowis/vendor/bundle/ruby/3.2.0/gems/grover-1.1.5/lib/grover.rb:51:in `to_pdf'
/Users/laykou/Projects/flowis/app/services/files/file_generator.rb:89:in `block in erb_pdf'
/Users/laykou/Projects/flowis/app/services/files/file_generator.rb:89:in `open'
/Users/laykou/Projects/flowis/app/services/files/file_generator.rb:89:in `erb_pdf'
/Users/laykou/Projects/flowis/app/reflexes/file_template_reflex.rb:15:in `preview'

```

@abrom Do you have any idea how start debugging it? What could `??=` mean?

**Comment by Laykou** [comment]
My bad, I see the issue was that my Ruby console was using `node 20.5` while web request was still running on `node 14.1` version and Grover requires version 16+. This is resolved now by the change in configuration - ensuring the web requests use the same supported node version.

**Comment by diegodev9** [comment]
> My bad, I see the issue was that my Ruby console was using `node 20.5` while web request was still running on `node 14.1` version and Grover requires version 16+. This is resolved now by the change in configuration - ensuring the web requests use the same supported node version.

Try to use nvm and create a file called .nvmrc with de node version inside (16.13.1) in the root folder of your project
It works like a charm.
