### ISSUE TITLE
`Grover::DependencyError: Cannot find module 'puppeteer'. The module was found in '/app/package.json' however, please run 'npm install' from '/app'`

### ISSUE THREAD

**Issue by TomasBarry** [Studiosity/grover#197]
I am looking to get Grover working on a site hosted on Heroku. I've solved the slug issues that others have had and have followed the documentation but I am still experiencing the error above:

* Grover version `1.1.5`
* Puppeteer version `19.4.0` (some restrictions here)
* `https://buildpack-registry.s3.amazonaws.com/buildpacks/jontewks/puppeteer.tgz` buildpack installed

I have not changed the configuration of Grover at all.

I feel as though something is missing but I am at a loss as to what this might be?

**Comment by stevenchern** [comment]
Did you try running 'npm install' in the console of heroku and restart the server?

I had a similar problem, a co-worker installed this Grover and puppeteer, when I got it, I had to install it again.

**Comment by TomasBarry** [comment]
@stevenchern - I'm a bit confused why that would be necessary. If it's in `package.json` it should already be installed when deployed right?

**Comment by cncerra1** [comment]
Does anyone else have an idea? I ran `npm install` in `/app` and... it still is throwing `Grover::DependencyError Cannot find module 'puppeteer'. The module was found in '/app/package.json' however, please run 'npm install' from '/app'`.

**Comment by SteveyblamWork** [comment]
Hi, we're still seeing this problem. Does anyone have any ideas?

Many thanks

**Comment by markedmondson** [comment]
> We used the heroku console to look for our node_modules folder, and saw that we did not have one (we had added a task that cleared out our node_modules folder after build so that the slug size was smaller - we had to undo this).

Hah, we were suffering this problem too and that's probably what's causing it. Thank you.

**Comment by alagos** [comment]
For me, installing with `npm install puppeteer` wasn't enough to install Chromium, but I managed to install it with
```
node node_modules/puppeteer/install.mjs
```

**Comment by SteveyblamWork** [comment]
We think we may have figured out the problem for us at least. We run our PDF generation on Heroku worker instances. We're pretty sure that worker instances don't run the node build pack when they're created. That's only run on the production instances.

Hope that helps others.
