### ISSUE TITLE
Question: is debug mode (headless false, devtools true) expected to close the browser immediately?

### ISSUE THREAD

**Issue by feliperaul** [Studiosity/grover#207]
When using the following debugging options:

```rb
debug: {
  headless: false,  
  devtools: true
}
```

Puppeteer opens (as expected), but it quits immediately (as if trying to print the pdf as soon as the page loads).

The only way I can actually debug is setting a `wait_for_function` to something that never happens (like "window.foo") and setting a very high `wait_for_function_options.timeout`.

Is this expected behavior? I'm assuming not, since the docs state `If showing the devtools, the browser will halt resulting in a navigation timeout`.

If not, any ideas what can be causing this?

**Comment by abrom** [comment]
You're best looking at the puppeteer documentation on how to use those settings: https://pptr.dev/guides/debugging/

It looks like puppeteer have changed the behaviour so the grover docs are out of date.

**Comment by TheBrockEllis** [comment]
I ran into the same problem today. Reading the Puppeteer docs, it looks like it requires two steps: setting headless to false, and then triggering a `debugger` to stop the browser. https://pptr.dev/guides/debugging#use-the-debugger-in-the-browser

I got this to work by turning off headless in my initializer:
```
# config/initializers/grover.rb
Grover.configure do |config|
  config.options = {
    product: 'chrome',
    executable_path: ENV['CHROMIUM_PATH'],
    debug: {
       headless: false,  # Default true. When set to false, the Chromium browser will be displayed
       devtools: true    # Default false. When set to true, the browser devtools will be displayed.
    }
  }
end
```

And then using Grover's `execute_script` option to place a debugger in the browser.

```
    png = Grover.new(absolute_html, { path: path, execute_script: 'debugger' }).to_png
```

Browser window popped up and then allowed me to navigate/explore/tinker. Not sure if this is the **correct** way, but it worked for me. ¯\_(ツ)_/¯

**Comment by abrom** [comment]
Yes, @TheBrockEllis, that would seem reasonable. You could really do anything that is going to stall the `execute_script` or similar. You could also do something like `wait_for_selector: '#does-not-exist'` or similar too.. but that will stall out after the specific wait timeout. 

@devsheva did you try read the documentation I linked to? Or follow the suggestion from @TheBrockEllis ?

**Comment by devsheva** [comment]
@abrom  Yes, I tried to follow @TheBrockEllis  suggestion, but didn't work for the specific situation on creating a PDF.
I'm going to try your suggestion about `wait_for_selector.

In the docs I didn't find something that could help, anyway I appreciate the help

**Comment by abrom** [comment]
Creating a PNG or a PDF, as far as Grover/Puppeteer are concerned are practically the same thing, especially for debugging as that will happen well before the export to PNG/PDF call is made. Can you elaborate on what "didn't work" means? What did happen? Can you include some sort of description of exactly what you're doing? Configuration options set, code used. etc..

**Comment by devsheva** [comment]
Sure. With "didn't work" I meant that I still have the same problem, which is that chrome gets closed instantly when trying to debug with headless mode off.

```ruby
# config/initializers/grover.rb
Grover.configure do |config|
      config.options = {
        print_background: true,
        wait_until: %w[load domcontentloaded],
        display_header_footer: true,
        debug: {
               headless: false,  # Default true. When set to false, the Chromium browser will be displayed
               devtools: true    # Default false. When set to true, the browser devtools will be displayed.
            }
      }
    end
```

Code example
`Grover.new(html_string).to_pdf`

This simple setup, nothing else. When i run it, Chrome window appears for a sec than gets closed

**Comment by abrom** [comment]
but your example doesn't appear to have either of the suggestions made by @TheBrockEllis or myself?! I have tested my suggestion and it definitely halts execution.

**Comment by devsheva** [comment]
Sorry for late answer @abrom. 
Probably my bad, since I just read that in [Debugging Section](https://github.com/Studiosity/grover?tab=readme-ov-file#debugging), it is mentioned this.

`The headless option disabled is not compatible with exporting of the PDF.`
