### ISSUE TITLE
Is it possible to generate a pageless continuous PDF?

### ISSUE THREAD

**Issue by Urist-McUristurister** [Studiosity/grover#210]
I need to generate a realllllly long document that contains a lot of differently sized images. Is there a way to generate a PDF with standard A4 width, but without splitting content into pages? Calculating page length in advance is not possible, so setting fixed size is not an option. :(

**Comment by abrom** [comment]
Good question. I'm not sure that would be possible with Grover as it is. You can evaluate (execute) a script after the page has loaded and before the export, but there is no way to do so in the context of the options (ie to update height). You're likely going to have to modify the processor JS https://github.com/Studiosity/grover/blob/main/lib/grover/js/processor.cjs#L260 before this to eval the height of the page and assign it to the export options..
