### ISSUE TITLE
Chromium and authorization

### ISSUE THREAD

**Issue by dvodvo** [Studiosity/grover#211]
This is not an issue per se with the existing commit, but a clarification issue.

[the ReadMe](https://github.com/Studiosity/grover#from-a-view-template) states that one can call an action, invoking a version of Chromium specified in an `executable_path`.

The working assumption is an action that has a regular HTML view and a PDF view.  Thus a respond_to block would be set as:
```
    respond_to do |format|
      format.html
      format.pdf do
        html = MyController.new.render_to_string({
          template: 'controller/view',
          layout: 'my_layout',
          locals: { :@instance_var => ... }
        })
        pdf = Grover.new(html, **grover_options).to_pdf
      end
    end
```

What happens if the `layout` is under some form of access control  ?  Does Chromium need to go through an authentication process or is it executing as the OS user?

**Comment by abrom** [comment]
What do you mean by:
> What happens if the layout is under some form of access control ? 

Not sure I've ever seen anyone try to put authorization "in the layout"?!

Grover will execute as the same user as your process.. but it is really unclear how that would have anything to do with access control, unless you're talking about file system access?? Which doesn't make much sense in the context of any sort of Rack access???
