### ISSUE TITLE
Problem install Grover on Google App Engine (GAE)

### ISSUE THREAD

**Issue by crivotz** [Studiosity/grover#219]
I am trying to integrate Grover into my project on Google App Engine (GAE) Standard, `ruby30` environment.
When I try to print a pdf I get the following message:

```
Grover::DependencyError (Cannot find module 'puppeteer'. The module was found in '/workspace/package.json' however, please run 'npm install' from '/workspace')
```

Everything works correctly in the development environment
This the line added to my `package.json` under `dependencies`

```
"puppeteer": "^21.7.0",
```

I tried to add also (with no result):
```
"scripts": {
  "gcp-build": "npm run build && npx @puppeteer/browsers install chromium --path /workspace/puppeteer"
},
"puppeteer": {
  "cacheDirectory": "/workspace/puppeteer"
},
```

Thanks for any tips

**Comment by abrom** [comment]
I can't say I know the ins and outs of GCP, but it does look like you're trying to install Chromium and not `puppeteer`. If you're wanting to manage the Chromium install path in that way, you're likely better off specifying `puppeteer-core` in the package.json as that WON'T install Chromium too..

You're running `npm run build` but AFAIK that won't do anything unless you have a build step specified? Do you? Installing the puppeteer node package will also install chromium see https://pptr.dev/#installation

I think you're best checking the logs.. check that puppeteer is actually being installed (the error says it isn't).

**Comment by crivotz** [comment]
For my actual project I solved the problem in other way without Grover but using puppeteer directly on a Google Cloud function.
Thank you very much for the support and the gem
