### ISSUE TITLE
Heroku - No usable sandbox! Update your kernel or see

### ISSUE THREAD

**Issue by danieldocki** [Studiosity/grover#22]
```2019-07-08T23:50:42.562794+00:00 app[web.1]: [0708/235042.049464:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.```

I set env to GROVER_NO_SANDBOX=true and added builpack https://github.com/jontewks/puppeteer-heroku-buildpack

what am I doing wrong?

**Comment by abrom** [comment]
@koenhandekyn did you see anything like this when testing your setup?

Can you confirm which version of the gem you have installed?

Can you confirm that the `GROVER_NO_SANDBOX` ENV var is definitely set?

**Comment by danieldocki** [comment]
> Can you confirm which version of the gem you have installed?

grover (0.7.3)

> Can you confirm that the `GROVER_NO_SANDBOX` ENV var is definitely set?

yes, is set

<img width="825" alt="Screen Shot 2019-07-09 at 00 22 56" src="https://user-images.githubusercontent.com/10542/60857100-b9e3be00-a1df-11e9-8477-2e84ac9ddb6a.png">

**Comment by abrom** [comment]
*doh* sorry that's on me. The README had been updated but I hadn't rolled a new release with the updated ENV flag name. Can you please update to 0.7.4

**Comment by abrom** [comment]
if you'd prefer not to update, you could use the 'old' ENV name for that flag:
```
heroku config:set CI=true [--remote yourappname]
```

**Comment by abrom** [comment]
(but of course going forward it will require the new `GROVER_NO_SANDBOX` ENV var)

**Comment by koenhandekyn** [comment]
i'm assuming it's indeed the env name

**Comment by danieldocki** [comment]
@abrom 

I updated gem and its working.

Thanks.
