### ISSUE TITLE
Where can i find an example of a docker image?

### ISSUE THREAD

**Issue by devsheva** [Studiosity/grover#221]
I'm trying to run Grover inside a container with the Rails app to generate PDF from there, but cannot find the right docker file

**Comment by abrom** [comment]
https://docs.docker.com/samples/rails/ maybe?

**Comment by devsheva** [comment]
I mean a docker image ready to run a Rails App with Grover, so that has node and puppeteer + chromium configured

**Comment by abrom** [comment]
it seems to me all you need to do is update the suggested example with Node then run `npm install` (assuming you have `puppeteer` in your `package.json`. 

Maybe something like https://github.com/timbru31/docker-ruby-node/blob/master/3.3/20/Dockerfile

I think it's best you try this yourself.

**Comment by devsheva** [comment]
Tried it but it's not that easy cause `puppeteer` needs Chromium to run, so I think there's more to do.

**Comment by abrom** [comment]
Installing Puppeteer will install Chromium. In any case, if you're unable to find someone else having done the work, you're likely going to have to do it yourself.

**Comment by ish-vasa** [comment]
@devsheva - any luck?
