### ISSUE TITLE
Failed to load error

### ISSUE THREAD

**Issue by antarr** [Studiosity/grover#226]
I'm getting this error when running in production, via render.com.

![image](https://github.com/Studiosity/grover/assets/974295/24dd37ea-c693-46e0-afd9-25441953f08e)

I'm using puppeteer 18.2.1 on node 14. Everything works fine when running on my local machine. No errors show up in the brower console or network tab.

.puppeteerrc.cjs
```
const {join} = require('path');

/**
 * @type {import("puppeteer").Configuration}
 */
module.exports = {
  cacheDirectory: join(__dirname, '.cache', 'puppeteer'),
};
```

**app/controller/text_controllers.rb**
```ruby
class TextController < ApplicationController
  def pdf
    case text.mime
    when 'application/pdf'
      send_file text.document.blob, type: 'application/pdf', disposition: 'inline'
    when 'text/html'
      content = text.document.blob.open(&:read)
      logger.warn "content: #{content}"
      pdf = Grover.new(content, format: 'A4').to_html
      send_data pdf, type: 'application/pdf', disposition: 'inline'
    else
      raise "Unsupported mime type: #{text.mime}"
    end
  end

private

  def text
    @text ||= LegiscanModel::Text.find_by(doc_id: params[:doc_id])
  end
end
```

**Comment by abrom** [comment]
I'm assuming you were able to find the cause of the problem here @antarr ? If the documentation could be improved to cover this case I would welcome a PR 😄 Or if you are able to provide a description of the cause that would likely help others in a similar situation

**Comment by antarr** [comment]
@abrom I just had to switch to WickedPDF for now

**Comment by abrom** [comment]
Well what I can see is that you're trying to use Grover to extract HTML and not a PDF

```
pdf = Grover.new(content, format: 'A4').to_html
```
which should be
```
pdf = Grover.new(content, format: 'A4').to_pdf
```

If you're returning HTML but telling the browser it's a PDF i'm not surprised the browser will give you that error message 😉

**Comment by erichstark** [comment]
Do you have any errors? I just found similar problem with render.com. It seems puppeteer is not available for the app even if you are install it manually.
