### ISSUE TITLE
Use puppeteer-ruby instead of puppeteer

### ISSUE THREAD

**Issue by elondres-mim** [Studiosity/grover#232]
Hi! Excellent project!

I'm hesitating on using grover for one of my websites because I currently don't have nodejs installed on my server and it seems like a headache to bring in yet another language ecosystem to update and whatnot. 
Has any thought been put into using the puppeteer-ruby gem (https://github.com/YusukeIwaki/puppeteer-ruby) instead of the puppeteer NPM package? I think this would simplify deployment quite a bit, but I'm not sure how much effort it would be. 

Thanks!

**Comment by abrom** [comment]
Thanks, although switching the "driver" really isn't on the cards. You are welcome to fork the grover gem and switch it yourself of course.

Note, I have spiked this concept before but the following were real blockers:
* The node puppeteer library is backed by Google.. support will generally be very good. Other libraries.. maybe
* The node puppeteer library outperformed Ruby based DevTools Protocol wrappers quite noticeably

Grover is itself a pretty thin wrapper around `puppeteer` so a re-write of the parts needed likely wouldn't be all that complicated.
