### ISSUE TITLE
Font styles won't apply in non-english languages

### ISSUE THREAD

**Issue by kstratis** [Studiosity/grover#24]
Hi,

First of all let me say great job with Grover!

Now, I recently used Grover to generate some PDFs for my web app and a very strange thing happened:

I'm using a particular Google font namely `Noto Sans` which I load in my template. The "problem" is that only english Characters are rendered with `Noto Sans`. Greek words (which I use) are rendered using the system defaults.

To add insult to the injury I used these to get a closer look:

```ruby
debug: {
  headless: false,  # Default true. When set to false, the Chromium browser will be displayed
  devtools: true    # Default false. When set to true, the browser devtools will be displayed.
}
```

and much to my surprise everything looked OK in Chromium.

I'm attaching the following screenshots to get a better idea of what I am talking about:

Final PDF result in **Chrome** (Notice that the English and the Greek words don't share the same font):
<img width="1236" alt="Screenshot 2019-07-10 12 01 26" src="https://user-images.githubusercontent.com/1859806/60956037-b39e3080-a30a-11e9-8e0c-e15e4dbe53fe.png">

and this is how it looks in **Chromium** using the devtools (Notice that now the English and Greek works do share the same font):
<img width="632" alt="Screenshot 2019-07-10 12 09 06" src="https://user-images.githubusercontent.com/1859806/60956487-987ff080-a30b-11e9-8723-d4a17afe54ac.png">

Any ideas on what this might be?

Thanks.

**Comment by abrom** [comment]
How are you loading the fonts? From your own server, or from a remote source?

I can't say I've done much (anything) wrt fonts with different languages. I would think if the font is loading and displaying for one language, it should do the same for the others?!

Could I suggest maybe trying to render a few different lines of text (on the same page) with various different fonts to see if there is any pattern there? 

Certainly a weird one!

**Comment by kstratis** [comment]
After much investigation it turns out that this was my mistake;

I was -erroneously- loading my fonts using this:

```html
<link href="https://fonts.googleapis.com/css?family=Noto+Sans&display=swap" rel="stylesheet">
```

instead of this

```html
<link href="https://fonts.googleapis.com/css?family=Noto+Sans&display=swap&subset=greek" rel="stylesheet">
```

Effectively I was cutting out the Greek subset and that's why the Greek fonts wouldn't properly render on the PDF. However you might ask why the Chromium screenshot (or better the web app itself) didn't have such problems: 

Turns out that when you specify a particular font that is not also served by the website itself the OS will try its best to match the required font. In case of `Noto Sans` the font was already included in macOS Mojave and was served by the OS each time a GUI app was launched (that is Chromium, Chrome etc) and that's why it did work in these cases.

Reference: https://support.apple.com/en-us/HT208968

Thanks for the lightning-fast response anyway.

**Comment by abrom** [comment]
Still strange that Chromium doesn't load it ? Or are you saying that the PDF was generated on a different platform? 

Either way, good to hear you got it sorted 👍

**Comment by kstratis** [comment]
Chromium did load everything but for the wrong reasons. That's why it blew up in my face when I run it in headless mode. 

Essentially when Chromium runs **in non-headless mode** it can read all the available system (OS) fonts and makes its best attempt to meet the demands of each app/website in terms of fonts. However when run in headless mode (which is what Grover mainly does) it doesn't have this capability and any special fonts specified in a website have to be loaded by the same website as a separate resource which in my case was missing as I hadn't include the Greek subset. 

That's why in the issue description you can see in the first screenshot the `serif` fallback for Greek while in the second (which has spawned Chromium UI) Greek render properly in `Noto Sans`.

Does this make any sense?

**Comment by abrom** [comment]
Yeah, interesting!
