### ISSUE TITLE
Multiple classes to wait for with wait_for_selector option.

### ISSUE THREAD

**Issue by Mohamed-Zkaria** [Studiosity/grover#242]
Hi, How can I make grover to wait on multiple classes? 
I tried to pass the option like this: `Grover.new(html, format: 'A4', wait_for_selector: [".map", ".pie"])` but it didn't work. Is there a different option for it?

**Comment by abrom** [comment]
see [waitForSelector documentation](https://pptr.dev/api/puppeteer.page.waitforselector); it does not support the form you're using, just a single selector. If you're wanting something more complicated then you'd likely use the [wait_for_function](https://pptr.dev/api/puppeteer.page.waitforfunction) method and pass in a function that queries both selectors are on the page. ie 
```
wait_for_function: "!!document.querySelector('.map') && !!document.querySelector('.pie')"
```

**Comment by Mohamed-Zkaria** [comment]
Thank you for your response! can I use this to wait for some time? like wait with settimeout?

**Comment by Mohamed-Zkaria** [comment]
Thank you appreciate your response.
