### ISSUE TITLE
wait_for_selector fails with extra_http_headers

### ISSUE THREAD

**Issue by Mohamed-Zkaria** [Studiosity/grover#243]
Hi, I am trying to use grover in a protected route and I am passing the following options to grover: 
```
headers = {'grover-token': ENV['TOKEN_KEY']}

grover_options = {
                format: 'A4', 
                wait_for_selector: ".map_renderer svg",
                timeout: 60000, 
                extra_http_headers: headers
            }
grover = Grover.new(path, **grover_options)

grover.to_pdf
```

And for some reason it fails to wait on the map selection whenever I pass extra headers and it fails after 30000ms even though I am modifying it. Any idea why this is happening? 

error log: 
```
Grover::JavaScript::TimeoutError (Waiting for selector `.map_renderer svg` failed: Waiting failed: 30000ms exceeded)
```

**Comment by abrom** [comment]
there are a lot of places timeouts can occur. At the moment the `timeout` option only applies to the request and conversion stages. Although TBH it likely makes sense for this option to also apply to the [Page.setDefaultTimeout](https://github.com/puppeteer/puppeteer/blob/main/docs/api/puppeteer.page.setdefaulttimeout.md)

For now though, you can provide the wait for selector timeout override via:
```
wait_for_selector_options: { timeout: 60000 }
```
See https://github.com/puppeteer/puppeteer/blob/main/docs/api/puppeteer.waitforselectoroptions.md

**Comment by Mohamed-Zkaria** [comment]
Thank you, appreciate your response.
