### ISSUE TITLE
 An `executablePath` or `channel` must be specified for `puppeteer-core`

### ISSUE THREAD

**Issue by devsheva** [Studiosity/grover#247]
I'm trying to use `puppeteer-core` package since I've already installed a chromium binary myself. What I did is setting the `PUPPETEER_EXECUTABLE_PATH` environment variable to point to chromium binary, but it leads to this error

`An executablePath or channel must be specified for puppeteer-core`

Setting the same env variable when using `puppeteer` npm works.

**Comment by abrom** [comment]
The error is trying to tell you how to fix it. You need to specify the `executable_path` option when configuring Grover. You could either do that globally (likely recommended) or per invocation. 

From the README: 
> The Chrome/Chromium executable path can be overridden with the `executable_path` option.

**Comment by devsheva** [comment]
That is the same of setting the env variable. I found it in the official puppeteer [docs](https://pptr.dev/api/puppeteer.configuration#properties:~:text=on%20the%20product.-,executablePath,-optional)

**Comment by abrom** [comment]
You're assuming that how ever you're setting that environment variable is going to make it's way through to the `nodejs` process that grover launches calling to the puppeteer library/chromium. There are plenty of reasons why this might or might not work but all of them depend on how your environment is setup. In this case it seems clear that what ever your setup is, trying to pass through the option through that ENV var is not working. Please defer to my previous comment about following the README

**Comment by devsheva** [comment]
Confirmed that manually setting the `executable_path` works. I'd like to now why the env variable doesn't work though
