### ISSUE TITLE
Undefined method #pack for nilClass on latest puppeteer release (23.1.0) 

### ISSUE THREAD

**Issue by Kay-pet** [Studiosity/grover#259]
Hi, 

I was getting the same error as this #252 . And when I make the change locally to `result["data"]&.pack("C*") || result.values.pack("C*")` in the `processor.rb` it works great, and so I was looking forward to this change happening as you had in the closed [PR](https://github.com/Studiosity/grover/pull/256).

I was waiting for this [PR](https://github.com/Studiosity/grover/pull/256) to go in and update the grover version but the PR was closed. I see you bumped to v1.1.10 with a fix and tested on puppeteer version 23.2.1, but I am on 23.1.0 and after bumping to grover v1.1.10 I am still experiencing the issue.

**Comment by abrom** [comment]
You're going to have to provide some more detail about the issue you're having. Grover 1.1.10 doesn't pass the data back in a format that would allow the change you've applied to make any difference so there is definitely something funny going on with your setup. If you've been modifying gems it is possible that you've accidentally left something in a corrupted state. 

Maybe try flush it out and start again:
```
gem cleanup grover
```

This is my setup which works just fine:

```sh
$ npm list puppeteer     
grover@1.1.10 /path/to/grover
└── puppeteer@23.2.1
```

```ruby
> Grover::VERSION
 => "1.1.10" 
> Grover.new('hey!').to_pdf
 => "%PDF-1.4\n......."
```

**Comment by Kay-pet** [comment]
Thanks for your quick reply, `gem cleanup grover` did not work but uninstalling the gem and reinstalling it did.

Thank you.

**Comment by leonardow-unep-wcmc** [comment]
Was using puppeteer 21.1.1, having the same issue after upgrade to 23.4.
Downgrade to 22.15 fixed the issue.

**Comment by abrom** [comment]
can you elaborate on what version of Grover you're using? Any other details you can share?

**Comment by leonardow-unep-wcmc** [comment]
> can you elaborate on what version of Grover you're using? Any other details you can share?

grover 1.1.7

using `browser_ws_endpoint` option, point to latest https://hub.docker.com/r/browserless/chrome locally.

**Comment by leonardow-unep-wcmc** [comment]
from the change log, look like I should upgrade grover to 1.10 to support v23. will try it later, thanks.

**Comment by abrom** [comment]
Correct 😉
