### ISSUE TITLE
Config for evaluateOnNewDocument?

### ISSUE THREAD

**Issue by rasmus0201** [Studiosity/grover#268]
Hi. I'm trying to add a script to the page before the script execution starts (to set some env configs for the in-page JS) 

This seems to be doable with `page.evaluateOnNewDocument()` in Puppeteer  - https://pptr.dev/api/puppeteer.page.evaluateonnewdocument

Is this something you could be interested adding to Grover?

**Comment by abrom** [comment]
hey @rasmus0201, that sounds like a useful feature. I'd welcome a PR for it 😄

**Comment by abrom** [comment]
would be a case of following a similar pattern (and location) of these: https://github.com/Studiosity/grover/blob/main/lib/grover/js/processor.cjs#L107-L185

Then add a test to ensure we don't get regressions, likely in https://github.com/Studiosity/grover/blob/main/spec/grover/processor_spec.rb

Likely something like: 
```
content 'when passing through evaluateOnNewDocument option' do
  let(:url_or_html) do
    <<-HTML
      <html>
        <body>
          Evaluate on new doc <span id="test">did not run</span>
          <script type="text/javascript">
            document.getElementById("test").innerHTML = window.preEvalContent;
          </script>
        </body>
      </html>
    HTML
  end
  let(:options) { { 'evaluateOnNewDocument' => 'window.preEvalContent = "ran!"' } }

  it { expect(pdf_text_content).to eq 'Evaluate on new doc ran!' }
end
```
i.e the only way this would pass is if that evaluate code had run before the page rendered. It wouldn't work with `executeScript` option for example.

**Comment by rasmus0201** [comment]
Thank you - I will try and make a PR 😊

**Comment by rasmus0201** [comment]
@abrom I've created https://github.com/Studiosity/grover/pull/269 

The new test is passing, though the whole test suite has some failures (at least on my machine)
