### ISSUE TITLE
Grover completes rendering before images are loaded

### ISSUE THREAD

**Issue by reefdog** [Studiosity/grover#30]
Howdy, and thanks much for an excellent gem!

I'm having trouble with renders (to JPEG, for what it's worth) occurring before the destination page has completed loading of all images. Thus, I get output with missing or only partially-loaded images; note the only halfway-loaded "False" meter (which appears in various states during different passes):

![grover-render](https://user-images.githubusercontent.com/4731/67435318-79068e00-f5b1-11e9-808d-6b57f9ec890e.jpeg)

Digging through the Puppeteer options, I _think_ what I want is to be able to set `waitUntil: 'networkidle0'` somewhere, but I'm not sure where or how. So:

1. Is this a known limitation, or…
2. Is there a Grover config option I can set that will instruct Puppeteer to wait until the page has completely finished loading before rendering the image, or…
3. Am I missing something?

<hr>

A bit more detail: this is a locally-rendered ERB template being passed in with image tags (and remote fonts) pointing to a variety of external servers. That particular image does happen to be served from a fairly slow HTTPS destination and generally takes 1-2 seconds to load. (Loaded in Chrome via Rails, that template fires DOMContentLoaded in ~850ms and Load in ~2.5s.)

**Comment by abrom** [comment]
How are you calling to Grover? Via middleware? Or passing it raw HTML? Or a URL ?

If it's via middleware or raw HTML then it's already using `waitUntil = 'networkidle0'`:
https://github.com/Studiosity/grover/blob/master/lib/grover.rb#L72

If it's a URL then it uses `waitUntil = 'networkidle2'`:
https://github.com/Studiosity/grover/blob/master/lib/grover.rb#L68

1. I use it 1,000+ times per day with middleware and URL methods that include plenty of images and I haven't seen that happen once (although I don't have any 'slow' resources). Also haven't seen anyone else report it

2. Per above, that's already the case although the method used is different depending on the way you're requesting content

3. Per the docs, `networkidle[0|2]` both only wait 500ms with no more than X network connections.. so if your image is taking 1-2 seconds to load it's possible that is too long for Chromium to wait. Although, also per the docs there is the `waitUntil: 'load'` option which waits until all dependent resources (such as images) have loaded. 

https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagegotourl-options
https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event

One possible solution would be to have the `waitUntil` property passed through as a configurable option so you can override it as needed (potentially on a per request basis if using the meta tags). 

But before going down that path, I'd suggest validating this by forking the project and swapping out the above two referenced lines with `request_options.waitUntil = 'load';` and see if that solves your problem.

**Comment by abrom** [comment]
Any feedback re the suggested solution @reefdog ?

**Comment by reefdog** [comment]
Hey @abrom, seriously appreciate the lightning-fast original response, and apologies for my slow reply. I'm part-time on the project that is using Grover, and wasn't able to respond again until now.

We're calling it directly by passing in a blob of HTML (no URL or middleware). I appreciate you pointing me to the specific LOC and doc sections; I've been crawling all over the Puppeteer docs but wasn't familiar enough with Grover's use of it to know which functions were actually used! This was terribly useful.

Your suggestion to force `waitUntil` to `load` is great; I'll give that a try and report back!

**Comment by abrom** [comment]
FYI @reefdog i've release v0.8.3 which adds support for specifying the `wait_until` option. Hopefully that'll help you with your issue

**Comment by reefdog** [comment]
@abrom Amazing! We ran into some issues on our side (unrelated to Grover) that prevented me from testing yet, but I'll be on this next week. 🙏

**Comment by reefdog** [comment]
So far, my testing with `wait_until: 'load'` has been working perfectly. Thank you @abrom!

**Comment by abrom** [comment]
Nice one 👍

**Comment by fkapsahili** [comment]
Hi, also from my side: Great Gem that saves me some nerves when generating PDF with Rails.

I too still have a difficulty when generating PDFs from an HTML template à la:

```ruby
      html = PdfController.new.render_to_string({
        template: "v1/pdf/ticket.html.erb",
        locals: { ticket },
      })

      options = {
        format: "A4",
        user_agent: "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0",
        wait_until: ["networkidle0", "load", "domcontentloaded", "networkidle2"],
      }

      # Test download
      pdf = Grover.new(html, options).to_pdf
      send_data pdf, filename: "ticket.pdf".
```

Everything works fine, but no external images (absolute URLs from websites) are displayed. The images from my template are on a public S3 bucket. I have also replaced them with other publicly available images from Google on a test basis, however these are not loaded when generating either.

The HTML file looks OK, however Grover doesn't seem to wait long enough. Access rights cannot be the problem.

I have already tested all wait_until options, but without success.

Do you have a tip for me? I would be very happy if I could fix this.

**Comment by abrom** [comment]
In the future suggest create a NEW issue and just reference any related issue ;) 

What have you tried to do to debug this? Have you read https://github.com/Studiosity/grover#debugging ?

What version of puppeteer have you installed? And, have you configured a specific browser binary?

**Comment by fkapsahili** [comment]
Thanks for the quick reply! Will be happy to open a new issue with a reference next time.

Have gone through the debug section, however I had the problem that Chromium appeared briefly, but only for about 0.5 seconds, and then closed again.

I have not configured any specific browser binaries and have installed puppeteer version 10.2.0.

I also just saw this issue, however explicitly overwriting the relative url (which should not be there in my case) did not help:
https://github.com/Studiosity/grover/issues/74#issuecomment-694432268

What is the easiest way to check which URL this is calling? Maybe it's really appending http://example.com or something.

**Comment by abrom** [comment]
That will happen if it has finished "waiting". 

Out of interest, can you try install Puppeteer 10.0.0. I have had issues myself with 10.1 and 10.2, albeit not exactly the same as you, but haven't had a chance to dig into it deeper as yet. 

You said you were already using absolute URLs so that shouldn't be it.

You can essentially pause the request to give you time to see what's going on. For example the [wait_for_timeout](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pagewaitfortimeoutmilliseconds) option for a fixed timeout (ms) or [wait_for_function](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pagewaitforfunctionpagefunction-options-args) for a dynamic wait. eg `wait_for_function: 'window.loaded'` then you could have a button on the page that sets `window.loaded=true` which you click once you're done inspecting the page/network tab on the inspector etc..

**Comment by fkapsahili** [comment]
Just worked directly with Puppeteer 10.0.0. Thanks for the tip!

**Comment by cristina-cowboy** [comment]
I have the exact same issue as @fkapsahili , been trying different config options for some time. I have finally reinstalled puppeteer with version 10.0.0 and it works 👍🏻 Will this be resolved for the latest version as well?
