### ISSUE TITLE
How to save PDF file using middleware?

### ISSUE THREAD

**Issue by porterbayne** [Studiosity/grover#36]
This gem is the cleanest, simplest, sturdiest view-to-PDF option for Rails I can find, and I have tried several (wicked; rails_pdf; html2pdf-rails).  Thank you!

The middleware to tack ".pdf" on to the end of a URL and have it output a PDF using my print styles is great.  Is there a way to have Rails save this file to my server's disk while using the middleware?  

This would be easier than refactoring my views to pass in local vars, and trying to get an absolute path for my styles working, to then use the `Grover.new(...).to_pdf` approach.

**Comment by abrom** [comment]
No problems! Although the bulks of the thanks really needs to go to the puppeteer project, Grover is really just a wrapper around it.

So just to confirm, what you've got is a Rails/Rack server and you're wanting to convert the HTML result from requests to PDF and then save them somewhere on the server?

Easy! Check out the `path` option:

https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#pagepdfoptions

It doesn't allow for passing in a dynamic path through say the global config, so you're likely going to need to add it as a meta tag in the response:

```
<meta name="grover-path" content="/my/unique/path-<%= env["action_dispatch.request_id"] %>.pdf">
```

and have something unique (like the request ID) in the name so you don't end up saving over the top of other requests.

Of course it's going to need to be a path that the user running your server can save to

**Comment by porterbayne** [comment]
I know it's "just a wrapper"... and I hate to start a (w)rap battle... but Grover's completeness and stability vs the others I tried saved me a ton of time this weekend.  :)

Ah, thank you for pointing out the `path` option, and for the speedy reply.  I will try it in a bit.  Cheers!

**Comment by porterbayne** [comment]
I am struggling to attach a PDF with ActiveStorage.  I am not trying to use `grover-path` after all because I am unsure how to save to a protected Rails tmp path, so that the file is not publicly accessible at all (it's sensitive health information).

So I am rendering with 
```ruby
rendered_string = MyController.new.render_to_string({...})
pdf = Grover.new(rendered_string).to_pdf
```

This generates a PDF, but I am unable to `.attach` it.  Trying variations on
```ruby
current_user.person.test_pdfs.attach(pdf)
# ActiveSupport::MessageVerifier::InvalidSignature
```

```ruby
current_user.person.test_pdfs.attach(StringIO.new(pdf), filename: "pdf_#{Time.zone.now}.pdf", content_type: "application/pdf")
 # Validation failed: Blob must exist
```

(Where my Person model `has_many_attached :test_pdfs`)

Any suggestions?  I've search Stack all morning but not grasping what to do.  I will be happy to create a PR with an update to the readme to show others, once I understand how to do it.  :)

**Comment by abrom** [comment]
I suspect if you're trying to use `attach` you'd need to assign the StringIO object to the `io` named variable. ie:
```
current_user.person.test_pdfs.attach(
  io: StringIO.new(pdf),
  filename: "pdf_#{Time.zone.now}.pdf",
  content_type: "application/pdf"
)
```

**Comment by porterbayne** [comment]
Oops. Can't believe I overlooked that.  Yes, that gets it to save as-expected.  Thanks!

New issue/question, I will start a new thread.

**Comment by porterbayne** [comment]
No new issue after all.  I just needed to read your docs more carefully to get the correct combo of middleware + ignore_path.  

Thank you for your help...  Please give me a paypal link to buy beer/donate somewhere.  :)

**Comment by abrom** [comment]
Nice one, glad to hear you worked it out.

No problems, happy to help
