### ISSUE TITLE
Is it a way to run a custom js script?

### ISSUE THREAD

**Issue by sasharevzin** [Studiosity/grover#37]
Like before saving, can I click on a link to expend some content and after save it pdf/image?

**Comment by abrom** [comment]
At the moment no, although the puppeteer API does support evaluating JS on the page so it should be possible:

https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#pageevaluatepagefunction-args

I haven't tested it, but I've created a branch that should do what you want:

https://github.com/Studiosity/grover/tree/add-evaluation-support

Just specify an `evaluate` option. Let me know if that works for you and I can look to rolling it into the release branch

**Comment by sasharevzin** [comment]
Worked! Thank you @abrom :)

**Comment by abrom** [comment]
Great! FYI I've rolled the change into a release (v0.9.2), although I've changed the option from `evaluate` to `execute_script` as it gives more context to what the option actually does.

**Comment by sasharevzin** [comment]
Wow, amazing. Thank you very much. Il update my gem file to use a new option :)
