### ISSUE TITLE
page_ranges option doesn't seem to be working

### ISSUE THREAD

**Issue by gdxn96** [Studiosity/grover#45]
```
Grover.new("https://stackoverflow.com/questions/5905054/how-can-i-recursively-find-all-files-in-current-and-subfolders-based-on-wildcard", format: "A4", page_ranges: "1-2", timeout: 0).to_pdf
```
This code intermittently gives me 7 or 8 pages in a pdf, rather than the expected 2. Is this a puppeteer issue? Or are the options incorrectly being formatted when passed to puppeteer? Or am I just using Grover incorrectly? 

Thanks in advance 😁

**Comment by abrom** [comment]
Usage looks fine to me. I've tested what you posted looped 30 times and each of them was the same two pages. Also tried `"1-3"` with the expected 3 pages shown.

The pageRanges option (which is how Grover passes `page_ranges` through to Puppeteer) takes a string so there's no need for any funny business in parsing etc. As such, Grover just pipes that option into Puppeteer so in this case it'd be more likely a Puppeteer/Chromium issue.

**Comment by gdxn96** [comment]
This helps, thank you 🙏
