### ISSUE TITLE
Rail's groover_options match my pdf.js file, but I get two separate results (half the styles work in the rails-generated PDF)

### ISSUE THREAD

**Issue by altjx** [Studiosity/grover#54]
New to this gem and appreciate on it.

I'm trying to figure out why I'm missing so many styles when I try to render content from within Rails compared to when rendering it just straight from the command line.

For example, here's what my controller has:

```
          grover_options = {
            format: 'Letter',
            margin: {
              top: '5px',
              bottom: '10cm'
            },
            viewport: {
              width: 640,
              height: 480
            },
            prefer_css_page_size: true,
            emulate_media: 'screen',
            cache: false,
            timeout: 0, # Timeout in ms. A value of `0` means 'no timeout'
            launch_args: ['--font-render-hinting=medium', '--no-sandbox'],
            wait_until: 'domcontentloaded',
            waitUntil: 'networkidle2'
          }
          grover = Grover.new('http://localhost:3000/test.html', grover_options)
          send_data grover.to_pdf, filename: "Report.pdf", type: 'application/pdf', disposition: :inline
```

and here's what I have inside of my Rails app's `pdf.js` file:

```
'use strict';

const puppeteer = require('puppeteer');

const createPdf = async() => {
  let browser;
  try {
    browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox']});
    const page = await browser.newPage();
    await page.goto(process.argv[2], {timeout: 3000, waitUntil: 'networkidle2'});
    await page.waitFor(250);
    await page.pdf({
      path: process.argv[3],
      format: 'Letter',
      full_page: true,
      prefer_css_page_size: true,
      emulate_media: 'screen',
      margin: { top: 36, right: 36, bottom: 20, left: 36 },
      printBackground: true
    });
  } catch (err) {
      console.log(err.message);
  } finally {
    if (browser) {
      browser.close();
    }
    process.exit();
  }
};
createPdf();

```

and I call it using:

`node pdf.js http://localhost:3000/test.html public/output.pdf`

Aren't these two pretty much configured to do the same thing? When I run `node` from the command line, I can see my table headers' backgrounds and everything looks fine. However, when I try to generate the PDF from the controller, the table header background doesn't show. It seems like some styles work (for example the h1 elements are applied) but some others don't.

I'm also running this in a digital ocean droplet, inside a container, so it's a little tough to debug.

Not sure what I'm doing wrong here. Any help would be greatly appreciated.

**Comment by abrom** [comment]
Hmm interesting one.. difficult to say exactly what's going on here. I would suggest you start by looking at your server logs to see that all of the assets are being requested. Are all of the assets being requested from the same file? Is there some sort of segregation of assets that might explain why some things render and others don't?

I'd also suggest take a look at: https://github.com/Studiosity/grover#relative-paths

Check to make sure you haven't got any path issues resulting in partially/incorrectly resolved assets?? Given you're passing in the URI instead of raw HTML it *should* behave the same as just requesting in Chrome/Chromium though..

I also noticed you've defined the "wait until" option twice, albeit slightly differently:

```
            wait_until: 'domcontentloaded',
            waitUntil: 'networkidle2'
```

I haven't tested this, but I suspect what you have there will end up sending `domcontentloaded` and NOT `networkidle2` to Puppeteer. As such it may be a case of Puppeteer simply snapshotting the page "too soon". Try remove the `domcontentloaded` option. Note you shouldn't actually need either of those. `networkidle2` is the default option within the Grover processor. See https://github.com/Studiosity/grover/blob/master/lib/grover/js/processor.js#L78

**Comment by altjx** [comment]
Hey @abrom 

I got rid of both of those options. Now I'm just trying a basic HTML file containing the following contents:

```
<table style="width: 100%" cellspacing="10" class="bordered">
  <tr>
    <th colspan="2" style="font-weight: bold; background-color: black !important;">Primary Point of Contact</th>
  </tr>
  <tr class="bordered">
    <td align="right" style="font-weight: bold;" width="20%">Name:</td>
    <td align="left">test</td>
  </tr>
</table>
```

The background of the table header is black when generating it from `node` command, but not from Rails. 

Still troubleshooting to see what's going on here.

**Comment by abrom** [comment]
The above is exactly what you get if you don't specify the `print_background: true` option. I see you have that set in your Node example but not the Rails one. You've sort of referenced that option in your second post, but you've used camel case and I can't say I've tried that out?! Might work?? Or maybe it doesn't. Can you try it in snakecase?

**Comment by altjx** [comment]
> The above is exactly what you get if you don't specify the `print_background: true` option. I see you have that set in your Node example but not the Rails one. You've sort of referenced that option in your second post, but you've used camel case and I can't say I've tried that out?! Might work?? Or maybe it doesn't. Can you try it in snakecase?

Yeah the options in the previous comment is from Rails. There's the `printBackground` option in there. Does it need `print_background` instead of `printBackground`? I'm mobile but will try it out as soon as I get the chance.

**Comment by altjx** [comment]
OMG. I cannot believe that it was due to that typo, lol. Thanks @abrom. Changed this from `printBackground` to `print_background` and it's working now.

Thanks SO much!!

**Comment by abrom** [comment]
Not a problem. So the "standard" form for symbols in Ruby is snake case but in Node it is camel case. As a result Grover does convert them before passing to Node (Puppeteer) but it's possible there is a bug in how that works that means existing 'camelised' options won't get passed through correctly. I'll look into it.

Glad you got it working
