### ISSUE TITLE
PDF Cover Pages are not rendered for non-middleware executions

### ISSUE THREAD

**Issue by MrLeebo** [Studiosity/grover#56]
Hi there, I appreciate the work you guys have done with this gem!

I'm not sure if this is intentional, but cover pages aren't rendered when you use direct execution,

```rb
# cover page will not render
Grover.new(pdf_report_url, front_cover_path: pdf_title_url).to_pdf
```

This is because the cover page logic exists in the middleware itself, but it is a little confusing because the grover instance receives the `front_cover_path` and `back_cover_path` options, it just doesn't do anything with them on its own.

Upon close examination of the README, the Cover Page does mention the middleware, but I figured the information about the global/meta-tag configurations was for the sake of the middleware execution, not that it was a complete restriction.

If the middleware restriction is intentional, I think it might help to point out the restriction explicitly. i.e. "This won't work for direct execution!"

As a fix, I used the same `combine_pdf` gem as the middleware uses:

```rb
  require 'combine_pdf'

  # ...

  def invoke(file_path)
    pdf = CombinePDF.parse(Grover.new(pdf_report_url).to_pdf)
    pdf >> CombinePDF.parse(Grover.new(pdf_title_url).to_pdf)
    pdf.save file_path
  end
```

This is an unrelated note and I don't expect you to try to resolve it, but when I tried to use middleware execution I would always get a Navigation Timeout error from the underlying puppeteer page.pdf() call. Running the same execution directly would quickly succeed. I don't have a good repro for that though (my app is a Single Page App that uses Hash Routing, which is why I ignored the middleware). I am assuming that the issue had to do with that app's architecture and isn't a middleware bug, but I figured I'd mention it in case that sparked an idea for you.

**Comment by abrom** [comment]
Hi @MrLeebo yes definitely an oversight. Those options shouldn't live on the Grover class, but only in the middleware. Of course the path option only really makes sense in the context of something that understands what the host to request it from is (a path as opposed to a URL). But I definitely see where the confusion is coming from here.

Of course using Grover like you've suggested would work just fine, and I'll happy accept a PR if you'd like to see something like that included in the README to explain that use case. One possible option would be to add some helper methods to allow Grover to do the cover/trailing page insertion essentially using something like you suggested, but the README is likely a better option given it would allow for more flexibility.

As for fixing the location of the cover page options I'll try to fit it in when I can. If you think you have a solution in the form of a PR that's fine too :)

Regarding the timeout issue, be sure to check your server has more than one worker. If you have just one it'll be tied up with the initial `.pdf` call. The secondary calls to fetch the content for assets etc made by Chromium will just sit there waiting for a worker to become free (which will only happen when the initial request times out). If you tail your server logs you'll no doubt see this. I use Grover in a bunch of scenarios with hash routing and have never had an issue. Under the hood it's using Puppeteer to drive Chromium so as long as it loads there, and as long as your server has enough workers to serve both the PDF request and the assets, then it should be golden
