### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function

### ISSUE THREAD

**Issue by altjx** [Studiosity/grover#58]
Hey @abrom,

I just rebooted my docker container and for some reason I'm getting this issue when trying to use Grover:

<img width="1052" alt="Screen Shot 2020-05-22 at 8 26 22 AM" src="https://user-images.githubusercontent.com/4023423/82667463-eccf4e80-9c05-11ea-8d80-bff29a330d5a.png">

Any suggestions on why this may be happening? I got this on another container too while trying to dockerize a rails app. Not sure why this may be happening. 

_**EDIT**_

Additional details from the console:

```
[10] pry(#<Consultants::ReportsController>)> grover = Grover.new('https://google.com', format: 'A4')
=> #<Grover:0x47462255799660 @url="https://google.com">
[11] pry(#<Consultants::ReportsController>)> grover.to_pdf
Grover::Error: TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
from /usr/local/rvm/gems/ruby-2.5.1/gems/grover-0.12.1/lib/grover/processor.rb:53:in `parse_package_error'
[12] pry(#<Consultants::ReportsController>)>
```

**Comment by altjx** [comment]
Got this resolved. Sorry about that. Forgot to install npm (thought it may have been optional for some strange reason reason).

Also had to install the following dependencies -- may be worth mentioning in the README as there will be additional errors:

`apt install -y libXss1 libgbm1 libasound2`

**Comment by abrom** [comment]
Glad to hear you worked it out. A quick google suggested it was a NodeJS version issue.

Hmm not so sure about those dependencies.. X screen saver? Mesa graphics library? Sound drivers? All sound either unrelated or very system specific (ie Mesa). There are so many graphics systems out there and I don't think the Grover readme is quite the place for setting those things up!
