### ISSUE TITLE
Detecting status codes?

### ISSUE THREAD

**Issue by HunterMeyer** [Studiosity/grover#61]
Say I'm asking Grover to generate a PDF from a URL.
Let's say that URL throws a 404 or 500.

Is there a way to read this from Grover?
Or perhaps pass some configuration to puppeteer to give us the status?

I'm returning the PDF file to the user. If the requested URL 404s, 500s, or something else I'd like to tell the user there was an error. I don't care if the PDF gets generated. I just don't want to send the user a PDF of a URL they weren't expecting.

**Comment by abrom** [comment]
When passing Grover a URL it will use the Puppeteer [page.goto](https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#pagegotourl-options) API. See https://github.com/Studiosity/grover/blob/master/lib/grover/js/processor.js#L79

Per the API docs Puppeteer will not raise any errors if there is an error type response (404s, 500s etc). The `goto` method does however return a HTTP response object which has a `status` method that would allow this to be dealt with. I wouldn't want to change the default behaviour but I'd happily accept a PR that adds a configuration option to check the response status and raise an exception if the status isn't a 2xx (ie likely using the [httpResponse.ok()](https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#httpresponseok) method). Once the exception has been raised in the Node processor it could be caught in Ruby land and dealt with however you want.

**Comment by HunterMeyer** [comment]
Awesome. I'll look into that. Thanks for pointing me in that direction.

**Comment by HunterMeyer** [comment]
I went ahead and just used the `execute_script` option to throw an error if the page URL doesn't match the intended URL (ie. on redirects).

```ruby
{
  execute_script: "if (window.location.href != '#{@url}') { throw 'url_mismatch' }"
}
```

This throws the following error in ruby:
```ruby
Grover::JavaScript::Error: Evaluation failed: url_mismatch
```

**Comment by abrom** [comment]
I suspect the `Evaluation failed` bit is because Node is trying to turn `url_mismatch` into a class. Try `throw new Error('url_mismatch')`

So long as the endpoint you're hitting redirects on errors this would work, although there might be some side effects for other sorts of redirects. I don't see the suggestion I have above would be hard to add. If I can find some time I'll have a crack at it.
