### ISSUE TITLE
ReadMe has several broken links

### ISSUE THREAD

**Issue by stephenq** [Studiosity/grover#62]
Example:
https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagescreenshotoptions

Correct:
https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pagescreenshotoptions

`GoogleChrome` -> `puppeteer` and `master` -> `main`

**Comment by abrom** [comment]
Happy to accept a PR
