### ISSUE TITLE
Zombie node processes

### ISSUE THREAD

**Issue by aganov** [Studiosity/grover#7]
First of all I want to thank you for the great gem. Unfortunately I'm experiencing some troubles with zombie ~~chrome~~ __nodejs__ processes growing increasingly. ~~It seems it's a wide-spread problem if you check `puppeteer` issue tracker. As I can see `browser.close()` is present but seems like not executed...~~ Are you experiencing same issues or have any idea how we can prevent this? Thanks!
```
grover v0.6.2
puppeteer v1.10.0
```

Edit: Seems like they are not chrome zobies but node zombies after all

```sh
alex             98350   0,0  0,4  4576400  31432 s000  S+   10:05pm   0:00.42 node -e try {\012  var puppeteer = require("puppeteer");\012} catch (e)
```

Maybe it's related to `schmooze` gem..

**Comment by abrom** [comment]
Hi @aganov,

No sorry, I haven't seen this problem before. There are quite a few 'moving parts' (ruby -> schmooze + node -> puppeteer -> chrome) and it could potentially be any link in the chain.

One possibility is that Schmooze will only kill the process when the object is garbage collected:

https://github.com/Shopify/schmooze/blob/master/lib/schmooze/base.rb#L37

Is it possible that your code is keeping the schmooze objects in scope?

**Comment by aganov** [comment]
I ended up there too, nodejs "zombies" are from `schmooze` gem, they are killed after `GC.start` so I think there is nothing that can be done, apparently this is how `schmooze` works :\

Thanks you! I'm closing this issue...
