### ISSUE TITLE
How to add a signature on footer

### ISSUE THREAD

**Issue by staycreativedesign** [Studiosity/grover#72]
How can I have it on the footer right hand side to have a line with initials on the bottom?

**Comment by abrom** [comment]
Not entirely sure I understand your question? If you're asking how you'd have the footer show some text (initials) and have them right aligned, then that's pretty easy. Just set the `footer_template` to something like:

```
'<div class='text right'>What ever text you want</div>'
```

ie:
```
Grover.new('<some site URI>', footer_template: '<div class='text right'>What ever text you want</div>').to_pdf
```

or via the global configuration options:
```
Grover.configure do |config|
  config.footer_template = '<div class='text right'>What ever text you want</div>'
end

....

Grover.new('<some site URI>').to_pdf
```

Of course if you're using the middleware you'd likely need to use the global configuration option ;)

See https://github.com/Studiosity/grover#header-and-footer-templates for the list of classes available for laying out the header/footer

**Comment by abrom** [comment]
Please note you would also need to specify `display_header_footer: true` per https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pagepdfoptions

**Comment by staycreativedesign** [comment]
thank you sir!

**Comment by staycreativedesign** [comment]
So I have this in my initializer

```
Grover.configure do |config|
  config.options = {
    format: 'A4',
    display_header_footer: true,
    header_template: "<div class='url'>foobar</div>",
    footer_template: "<span class=;pageNumber'></span>/<span class='totalPages'></span>",
    margin: {
          bottom: 70,
          left: 25,
          right: 35,
          top: 30,
    },
    print_background: true,
    viewport: {
      width: 640,
      height: 480
    },
    prefer_css_page_size: true,
    emulate_media: 'screen',
    cache: false,
    timeout: 0, # Timeout in ms. A value of `0` means 'no timeout'
    launch_args: ['--font-render-hinting=medium'],
    wait_until: 'domcontentloaded'
  }
end
```

  def contract
    html = render_to_string({
      template: 'pages/contract',
      layout: 'contract.haml'
    })
    pdf = Grover.new(html).to_pdf
    send_data pdf
  end

nothing in the footer  what I do wrong here?!

**Comment by abrom** [comment]
Likely related to the invalid HTML class attribute.. semicolon instead of a quote

**Comment by abrom** [comment]
You'd also likely want to wrap the spans in a div with the `text` class. The default with chrome is **really** small text. It's there, you just can't see it unless you zoom right in. Ie

```
<div class='text'>what ever</div>
```

**Comment by abrom** [comment]
that was in my example above ;)

**Comment by staycreativedesign** [comment]
Thank you sir!

**Comment by staycreativedesign** [comment]
```
%footer{:style => "font-size:16px;margin-left: 80%;"}
```
This hack works

**Comment by abrom** [comment]
Ok to resolve this @staycreativedesign  ?

**Comment by staycreativedesign** [comment]
> Ok to resolve this @staycreativedesign ?

Yes it is :)
