### ISSUE TITLE
How to add css or stylesheets to pdf

### ISSUE THREAD

**Issue by staycreativedesign** [Studiosity/grover#73]
How is it possible to add css or stylesheets to grover?

**Comment by abrom** [comment]
What ever you have in the page is what will get rendered. If you want to test what something is going to look like you can open the page in Chrome then save it as a PDF. That's pretty much what Grover does ;)

**Comment by staycreativedesign** [comment]
Sweet I basically just dropped this in the file and it worked
`   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">`

**Comment by k2director** [comment]
@staycreativedesign  Thanks for posting that <link>, it brought my Bootstrap styles online!
