### ISSUE TITLE
Issue setting up sandbox

### ISSUE THREAD

**Issue by Tomgeo64** [Studiosity/grover#75]
Failed to launch the browser process! [0730/163311.689983:FATAL:zygote_host_impl_linux.cc(117)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox. 

I get this error message in my browser when launching my Rails app. I went to the URL and it says install it from build/update-linux-sandbox.sh, which is not a file on my system nor do I know how to get it. I installed pupeteer with npm install and grover with a bundle install.

I am developing in a linux subsystem on a windows PC.

Help would be appreciated.

**Comment by abrom** [comment]
First hit when Google searching is: https://github.com/puppeteer/puppeteer/issues/3451 suggest you start there.

If your only recourse is to run puppeteer without a sandbox, the README explains how to do this. Ie. using the ENV `GROVER_NO_SANDBOX=true`. Alternatively you can achieve the same thing with:

```
Grover.configure do |config|
  config.launch_args: ['--no-sandbox', '--disable-setuid-sandbox']
end
```
(or similar).

**Comment by abrom** [comment]
Did you resolve this @Tomgeo64  ?

**Comment by Tomgeo64** [comment]
Sort of, I just enabled the no sandbox settings.

**Comment by abrom** [comment]
Sounds like it's a kernel configuration issue then. Given you have a solution, ok to close the issue?

**Comment by Tomgeo64** [comment]
sure

**Comment by JuanVqz** [comment]
In Heroku, I had the same issue and I solved it as @abrom said setting up the `GROVER_NO_SANDBOX=true` variable.
Thank you for your arduous work @abrom
