### ISSUE TITLE
Blank page depending on margins

### ISSUE THREAD

**Issue by altjx** [Studiosity/grover#77]
Hi there. I'm using Grover for my Ruby on Rails application and, while it works perfectly fine for the most part, I do have an issue from time to time where the contents will go right to the end of the page, and the next page will be blank. See screenshot below:

![image](https://user-images.githubusercontent.com/4023423/89127132-51860f80-d4b9-11ea-93c6-130c098fd308.png)

Here's what my options look to generate this:

```
body_html = render_to_string template: 'common/report_templates/generate_pdf.html.erb', layout: false
header_template = render_to_string template: 'common/report_templates/shared/report_header.html.erb', layout: false
              footer_template = render_to_string template: 'common/report_templates/shared/report_footer.html.erb', layout: false
              grover_options = {
                format: 'Letter',
                full_page: true,
                prefer_css_page_size: false,
                emulate_media: 'screen',
                cache: false,
                timeout: 0, # Timeout in ms. A value of `0` means 'no timeout'
                launch_args: ['--font-render-hinting=medium', '--no-sandbox'],
                margin: { top: 75, right: 30, bottom: 44, left: 30 },
                print_background: true,
                scale: 0.75,
                display_header_footer: true,
                header_template: header_template,
                footer_template: footer_template
              }
final_pdf = CombinePDF.new
final_pdf << CombinePDF.parse(Grover.new(body_html, grover_options).to_pdf)
file_path = "tmp/test"
final_pdf.save file_path
```

It seems that when this happens, I have to constantly adjust the bottom margin to a lower value so that the content can extend a little further down the page, but then this takes away from the footer.

The bottom of the page that has the blank page after it looks like this:

```
<p style="page-break-after: always;">&nbsp;</p>
```

What I suspect to be happening is something like this:

```
- a bunch of text
- page break
- a bunch of text
- page break
```

If `a bunch of text` is at the very bottom of a page, then the page break paragraph will appear on a new page, at which point it inserts a page break page _after_ that paragraph that declares the page break, causing it to create a blank page.

This is what I think is happening:

![image](https://user-images.githubusercontent.com/4023423/89127486-cbb79380-d4bb-11ea-84ba-685a7835a909.png)

Here's what my Rails code looks like:

```
    <% items.each do |item| %>
        <% unless item == items[0] %>
            <p style="page-break-after: always;">&nbsp;</p>
        <% end %>
        <%= render partial: "common/report_templates/shared/item" %>
    <% end %>
```

Is there any way I can get around this by chance?

**Comment by abrom** [comment]
Not really a grover thing, rather a chromium page render issue. In any case, it's a tricky one to solve as the PDF is being generated exactly how you're telling it to! One option might be to use a PDF parser library (such as `pdf-reader`) to read the last page contents, if it's just the header/footer then use something like `combine_pdf` to remove the last page. 

Of course you could also maybe just try flip your page break logic around?

```
    <% items.each do |item| %>
        <%= render partial: "common/report_templates/shared/item" %>
        <% unless item == items.last %>
            <p style="page-break-after: always;">&nbsp;</p>
        <% end %>
    <% end %>
```

**Comment by abrom** [comment]
Hmm although with your current logic that should be the same, suggesting that you've got some content after the last "item" partial render

**Comment by altjx** [comment]
Yeah exactly. I realized this shortly after posting this lol. I think I have to figure out a way to make these page breaks pretty much invisible so that it doesn't roll over into another page when it's at the bottom of the content.

**Comment by wnm** [comment]
@altjx ever find a solution for this? 😊
