### ISSUE TITLE
Multi Page PDF Generation

### ISSUE THREAD

**Issue by esparkman** [Studiosity/grover#78]
Hey guys. I have Grover implemented. However it isn't working quite as I would expect. I have Reports feature where a User can export a report as a PDF. This report is essentially a table that could have 1 or 1000 rows. When exporting all I get back is the first page or the current viewport. What do I need to setup so that I'm getting shots of the content below the fold?

**Comment by abrom** [comment]
Hi @esparkman

Can you provide any details about how you're using it? Passing HTML directly? Or using the middleware?

In either case, what configuration have you set?

Unless you tell it to, or your page content tells it to, the content will be all pages..

Grover just passes the HTML through to puppeteer (chromium) so it's going to come down to how your content renders in chromium. What happens if you try view the HTML page in the print preview window for chrome? Or from the print preview try save add PDF. I suspect you'll see the same issue there.

**Comment by esparkman** [comment]
I do in fact see the same issue when using Chromium to manually save the page as PDF.

I'm using the example initializer config, plus adding `full_page: true`
```
# config/initializers/grover.rb
Grover.configure do |config|
  config.options = {
    full_page: true
    format: 'A4',
    margin: {
      top: '5px',
      bottom: '10cm'
    },
    prefer_css_page_size: true,
    emulate_media: 'screen',
    cache: false,
    timeout: 0, # Timeout in ms. A value of `0` means 'no timeout'
    launch_args: ['--font-render-hinting=medium'],
    wait_until: 'domcontentloaded' 
  }
end
```

We have a Vue frontend that handles the layout, we pass the data over to the Rails app and run it through resque to generate the file and then have little polling service to check for the status.

Do I need to pass the page_count, page_size, etc to handle multi page snapshots?

**Comment by abrom** [comment]
`full_page` is an option for screenshoting images, not PDFs:

https://github.com/puppeteer/puppeteer/blob/v5.2.1/docs/api.md#pagescreenshotoptions

Right, so you've configured it to wait until the DOM content has loaded.. that happens pretty quickly. You're then going off and fetching results, but Grover (Puppeteer) doesn't know to wait for that! One option you could try would be to use the `wait_for_selector` option. See https://github.com/Studiosity/grover#configuration  i.e. have your page add a class or attribute when the content has finished loading, and tell Grover to wait for that class before creating the PDF.

ie `wait_for_selector: 'body.content_loaded'` or similar.. 

Note, Puppeteer does actually support quite a few "wait for ..." methods, but at the moment only the wait for selector method has been implemented.

**Comment by esparkman** [comment]
Sorry for the delayed response. I ended up figuring out what was happening. We had an outer most container div that was specifying a set height, so it was never actually getting a full view of all the results. Thanks again for the prompt responses.
