### ISSUE TITLE
Grover::JavaScript::Error (Navigation failed because browser has disconnected!)

### ISSUE THREAD

**Issue by ckhall** [Studiosity/grover#80]
on Heroku, receiving this error when calling `.to_pdf`.

Followed all the instructions on setting up puppeteer on heroku.  Any ideas here?

**Comment by abrom** [comment]
Going to need a lot more information.

1. have you followed all of the Heroku setup instructions? https://github.com/Studiosity/grover#running-on-heroku
2. what is your code setup before the call to `.to_pdf`?
3. what versions of things have you got installed? Grover? Puppeteer? Chromium?
4. what have you tried to figure this out?
5. have you tried searching the web for the error? I found many results. It may be that someone else has had this issue!

**Comment by ckhall** [comment]
@abrom 

1. yes, to the letter.
2.  ```
        html = render_to_string('report.html.erb', layout: false)
        pdf = Grover.new(
          html,
          height: '11in',
          width: '8.5in',
          landscape: true,
          margin: {
            top: '0px',
            bottom: '0px',
            left: '0px',
            right: '0px'
          }
        ).to_pdf
```
3. grover v0.13.1, puppeteer v5.2.1, chromium ? (as i understand, puppeteer downloads latest?)
4. google "Navigation failed because browser has disconnected!" - nothing i have come across pertains to ruby or heroku.
5. see #4.

**Comment by ckhall** [comment]
chromium version is `Chromium 86.0.4240.0 (r800071)` according to puppeteer changelog

**Comment by ckhall** [comment]
ok, figured it out.  had to remove jemalloc buildpack.  `https://github.com/gaffneyc/heroku-buildpack-jemalloc.git` specifically and not start processes using `jemalloc.sh`. may want to add a note to the readme for Heroku section.

**Comment by abrom** [comment]
I'll happily accept a PR ;)

**Comment by kladaFOX** [comment]
> ok, figured it out. had to remove jemalloc buildpack. `https://github.com/gaffneyc/heroku-buildpack-jemalloc.git` specifically and not start processes using `jemalloc.sh`. may want to add a note to the readme for Heroku section.

Thanks MAN

**Comment by mikkelwf** [comment]
It's an issue that this doesn't work with jemalloc enabled

**Comment by Fire-Dragon-DoL** [comment]
Oh wow, I think it might be worth mentioning in the README. I just lost 2 days on this and I would have not have considered grover at all if I knew I couldn't use jemalloc (yes, it saves so much memory).

Thank you for opening this issue, I would have kept searching forever.
