### ISSUE TITLE
JSON::ParserError: A JSON text must at least contain two octets!

### ISSUE THREAD

**Issue by ckhall** [Studiosity/grover#81]
```
"/Users/ckhall/Projects/project/vendor/bundle/ruby/2.6.0/gems/json-1.8.6/lib/json/common.rb:155:in `initialize'",
"/Users/ckhall/Projects/project/vendor/bundle/ruby/2.6.0/gems/json-1.8.6/lib/json/common.rb:155:in `new'",
"/Users/ckhall/Projects/project/vendor/bundle/ruby/2.6.0/gems/json-1.8.6/lib/json/common.rb:155:in `parse'",
"/Users/ckhall/Projects/project/vendor/bundle/ruby/2.6.0/gems/grover-0.13.1/lib/grover/processor.rb:84:in `call_js_method'",
"/Users/ckhall/Projects/project/vendor/bundle/ruby/2.6.0/gems/grover-0.13.1/lib/grover/processor.rb:20:in `convert'",
"/Users/ckhall/Projects/project/vendor/bundle/ruby/2.6.0/gems/grover-0.13.1/lib/grover.rb:50:in `to_pdf'",
"/Users/ckhall/Projects/project/app/services/create_order_labels_with_routing.rb:45:in `create_order_labels'",
```

did some digging and found the cause, at least as far as I can get anyways.  Line 84 of `lib/grover/processor.rb` where the value of `input` is a single newline `"\n"` cannot be parsed as json (obviously).

The size of the html string being passed to grover, with newlines and extraneous whitespace removed, is `3352813` bytes so I can only assume this may very well be the actual root cause.  The expected result is a little over 300 pages of labels.

I do not know what would cause a single newline to be returned on line 81 of `lib/grover/processor.rb`.  Smaller html strings are converted ok.

debug session:

```
    79: def call_js_method(method, url_or_html, options) # rubocop:disable Metrics/MethodLength
    80:   stdin.puts JSON.dump([method, url_or_html, options])
    81:   input = stdout.gets
    82:   raise Errno::EPIPE, "Can't read from worker" if input.nil?
    83: 
    84:   status, message, error_class = JSON.parse(input)
    85: 
    86:   if status == 'ok'
    87:     message
    88:   elsif error_class.nil?
    89:     raise Grover::JavaScript::UnknownError, message
    90:   else
    91:     raise Grover::JavaScript.const_get(error_class, false), message
    92:   end
    93: rescue JSON::ParserError => e
    94:   binding.pry
 => 95:   puts e.message
    96:   raise e
    97: rescue Errno::EPIPE, IOError
    98:   raise Grover::Error, "Worker process failed:\n#{stderr.read}"
    99: end

[1] pry(#<Grover::Processor>)> input
=> "\n"
[2] pry(#<Grover::Processor>)> url_or_html.to_s.bytesize
=> 3352813 
[3] pry(#<Grover::Processor>)> options
=> {"height"=>"11in",
 "width"=>"8.5in",
 "printBackground"=>true,
 "emulateMedia"=>"screen",
 "timeout"=>0,
 "margin"=>{"top"=>"0px", "bottom"=>"0px", "left"=>"0px", "right"=>"0px"}}
```

continuing to run `stdout.gets` shows:

```
[4] pry(#<Grover::Processor>)> stdout.gets
=> "<--- Last few GCs --->\n"
[5] pry(#<Grover::Processor>)> stdout.gets
=> "e [21931:0x10280c000]    94948 ms: Mark-sweep 392.1 (398.2) -> 350.1 (356.2) MB, 0.6 / 0.0 ms  (+ 3.1 ms in 2 steps since start of marking, biggest step 3.0 ms, walltime since start of marking 723 ms) (average mu = 0.992, current mu = 0.995) finalize increm[21931:0x10280c000]    97435 ms: Mark-sweep 734.1 (740.2) -> 398.1 (404.2) MB, 151.6 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 1797 ms) (average mu = 0.947, current mu = 0.939) allocation f\n"
[6] pry(#<Grover::Processor>)> stdout.gets
=> "\n"
[7] pry(#<Grover::Processor>)> stdout.gets
=> "<--- JS stacktrace --->\n"
[8] pry(#<Grover::Processor>)> stdout.gets
=> "\n"
[9] pry(#<Grover::Processor>)> stdout.gets
=> "==== JS stack trace =========================================\n"
[10] pry(#<Grover::Processor>)> stdout.gets
=> "\n"
[11] pry(#<Grover::Processor>)> stdout.gets
=> "    0: ExitFrame [pc: 0xde9fb3dbe3d]\n"
[12] pry(#<Grover::Processor>)> stdout.gets
=> "Security context: 0x06429f2d6781 <JSObject>\n"
[13] pry(#<Grover::Processor>)> stdout.gets
=> "    1: toJSON [0x6426d7a0b09] [buffer.js:~979] [pc=0xde9fb6bbfa5](this=0x06425fcc6561 <Uint8Array map = 0x642e9fd59d1>)\n"
[14] pry(#<Grover::Processor>)> stdout.gets
=> "    2: arguments adaptor frame: 1->0\n"
[15] pry(#<Grover::Processor>)> stdout.gets
=> "    3: InternalFrame [pc: 0xde9fb38ee75]\n"
[16] pry(#<Grover::Processor>)> stdout.gets
=> "    4: EntryFrame [pc: 0xde9fb3892c1]\n"
[17] pry(#<Grover::Processor>)> stdout.gets
=> "    5: builtin exit frame: stringify(this=0x06429f2cae89 <Object map = 0x642e9f842a9>,0x0642141026f1 <undefined>,0x0642141026...\n"
[18] pry(#<Grover::Processor>)> stdout.gets
=> "\n"
```

grover gem version: 0.13.1
puppeteer version: 5.2.1 (also tried 5.3.0)
chromium version: 

Would you happen to have any insights into why this could be happening?  Happy to create puppeteer issue if necessary, but wanted to post here as this could be considered a bug on expecting json at `lib/grover/processor.rb:84`.

Look forward to hearing what you might think about this. Thanks.

**Comment by ckhall** [comment]
actually, think i may have found the root cause

```
[1] pry(#<Grover::Processor>)> stderr.read
=> "FATAL ERROR: invalid table size Allocation failed - JavaScript heap out of memory\n 1: 0x10003d041 node::Abort() [/Users/ckhall/.nvm/versions/node/v10.18.1/bin/node]\n 2: 0x10003d24b node::OnFatalError(char const*, char const*) [/Users/ckhall/.nvm/versions/node/v10.18.1/bin/node]\n 3: 0x1001b8fd5 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/ckhall/.nvm/versions/node/v10.18.1/bin/node]\n 4: 0x100586f32 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/ckhall/.nvm/versions/node/v10.18.1/bin/node]\n 5: 0x1006cddee v8::internal::HashTable<v8::internal::NumberDictionary, v8::internal::NumberDictionaryShape>::EnsureCapacity(v8::internal::Handle<v8::internal::NumberDictionary>, int, v8::internal::PretenureFlag) [/Users/ckhall/.nvm/versions/node/v10.18.1/bin/node]\n 6: 0x1006d6a95 v8::internal::Dictionary<v8::internal::NumberDictionary, v8::internal::NumberDictionaryShape>::Add(v8::internal::Handle<v8::internal::NumberDictionary>, unsigned int, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyDetails, int*) [/Users/ckhall/.nvm/versions/node/v10.18.1/bin/node]\n 7: 0x10051643f v8::internal::(anonymous namespace)::DictionaryElementsAccessor::AddImpl(v8::internal::Handle<v8::internal::JSObject>, unsigned int, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, unsigned int) [/Users/ckhall/.nvm/versions/node/v10.18.1/bin/node]\n 8: 0x10069f65c v8::internal::JSObject::AddDataElement(v8::internal::Handle<v8::internal::JSObject>, unsigned int, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::ShouldThrow) [/Users/ckhall/.nvm/versions/node/v10.18.1/bin/node]\n 9: 0x1008058c9 v8::internal::Runtime::SetObjectProperty(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::LanguageMode) [/Users/ckhall/.nvm/versions/node/v10.18.1/bin/node]\n10: 0x1006080bc v8::internal::Runtime_KeyedStoreIC_Slow(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/ckhall/.nvm/versions/node/v10.18.1/bin/node]\n11: 0x1a4416a5be3d \n"
```

**Comment by ckhall** [comment]
is there a way to pass arguments to the node process in grover?

**Comment by ckhall** [comment]
Happy to submit a PR for the json parse error.  nothing i try regarding setting max memory for node process seems to work.  using smaller iterations and combine_pdf gem to get this to work.

**Comment by abrom** [comment]
Interesting problem @ckhall !

I've never tried to convert a document that large, but other folks seem to suggest that passing a larger memory allocation with the `max-old-space-size` v8 flag to node would help? ie `node --max-old-space-size=4096 processor.js` or using and ENV var `NODE_OPTIONS="--max-old-space-size=4096" node processor.js`. Was that one of the things you tried? Assuming your 3GB data (along with the rest of the app) would fit in 4GB of memory. Might need even more? A memory profiler might give you some hints there.

The option could be passed in via the call to `Open3.popen3` in `Grover::Processor#spawn_process` method, although it would definitely need to be something configured rather than the default. Given it's something likely passed through to the shell I'd think it'd be a good idea to guard it from being something passed through by the metadata options parser.

In terms of catching the error, it sounds like you're on to something. I would think just catch the `JSON::ParserError` in `Grover::Processor#call_js_method` like you've suggested. You could just add that to the list of other errors? Ie:
```
rescue Errno:EPIPE, IOError, JSON::ParserError
  raise ....
end
```
I'm not sure the context of the type of error would really add much. The contents of `stderr.read` would no doubt be of most benefit.

**Comment by abrom** [comment]
Yes, PR sounds great. Hmm that's a pity.. although it sounds like there is at least a work around.

From the stack trace it does look like the exception is coming out of v8 so it could be worth following up with the Puppeteer and/or Chromium team to see if they have any suggestions?

**Comment by ckhall** [comment]
So i did go down the `--max-old-space-size` route, and got up to 8G before giving up.

In our case it was the inclusion of 2 webfonts. when i removed them, and replaced with Arial, size of the resulting pdf went from 325MB to 1.3MB!

In researching this, this is an upstream issue with chromium and how it renders pdfs.  To test it even thoroughly, i saved the rendered html that was being passed to grover and opened it in chrome on my macbook.  saving as pdf resulted in a 325MB file as well.

I agree on adding it to the list of other errors.   I'll fork and create a PR for that.  Thanks for the insights!

**Comment by abrom** [comment]
Interesting.. sounds like giving the chromium team a prod RE the existing issue is likely the best option then
