### ISSUE TITLE
Can't override display_url when using middleware

### ISSUE THREAD

**Issue by anamba** [Studiosity/grover#83]
If I'm reading this correctly, there is no way to override the detected display_url option when using the middleware.
https://github.com/Studiosity/grover/blob/main/lib/grover/middleware.rb#L104

I need to do this because the Rails app is running in a docker container, so the url that Grover needs to use is different from the one I'm using to access from the host.

**Comment by abrom** [comment]
You can override it with meta options. See:

https://github.com/Studiosity/grover/blob/main/lib/grover/options_builder.rb#L13-L15

The order of precedence with the options is:
* Global options
* instance options (ie what is passed in to the Grover initialiser - in this case in the middleware)
* meta options (for HTML content conversion).

In your case you'd use something like this in your HTML:
```
<meta name="grover-display_url" content="...some other URI..." />
```

Although TBH I'm not sure I'm seeing why the Rails app running in a docker container changes anything?!

Assuming you have some sort of routing front end between whom ever is requesting things and the backends providing it, any additional requests for assets etc that need to be made would end up just bubbling back up to the front end router then back down to the back ends again. Just so long as the backends can make requests of the front end..

**Comment by anamba** [comment]
Hmm, I did try using a meta tag just like that but it didn't seem to help.

I am using docker for development, not production. So I access it via a non-public URL like myapp.lvh.me:3000 or 192.168.0.10:3000, neither of which would work within the container.

It does work as expected if I use ngrok or similar to create a public URL, but (1) that can be a long round trip vs. localhost and (2) I generally don't want to expose my development environment to the world anyway.

**Comment by abrom** [comment]
Can you maybe explain what the actual problem is?

**Comment by anamba** [comment]
Oh, I thought I had explained it, sorry.

Very simple, external resources like stylesheets and images don't load when using the middleware, due to my docker setup. They do load if I do a `curl http://localhost/route.pdf -o test.pdf` from within the docker container, but if I browse to `http://myapp.lvh.me:3000/route.pdf` on the host, that url won't work from within the container (inside the container, the app listens on port 80, not 3000), so no external resources.

So I want to fix that by setting `display_url` to `http://localhost/`, but that doesn't appear to be an option when using the middleware.

Setting display_url works fine when not using the middleware (I have a mailer that sends pdf attachments).

**Comment by anamba** [comment]
Hmm, I realized that actually the `display_url` setting has no effect because it's already done the preprocessing here:
https://github.com/Studiosity/grover/blob/main/lib/grover/middleware.rb#L102

**Comment by abrom** [comment]
Hmm indeed. It sounds like what you want then is to overload the `root_url` for the middleware then?

One thought would be to modify the middleware initialiser then pass the desired root URL through there?

ie

```
def initialize(app, *args)
  ....
  @root_url = args.last[:root_url] if args.last.is_a? Hash
end
```

then configure the middleware with:

```
config.middleware.use Grover::Middleware, root_url: 'http://localhost/'
```

That or it could be configured through the global config?

Happy to accept a PR, just ask that you include a spec to test it. You can see an example of how it might be tested at spec/grover/middleware_spec.rb#L451 Just overload the `mock_app` to have the config passed through :)

**Comment by anamba** [comment]
Thanks, I will try that out and open a PR once it looks good.
