### ISSUE TITLE
Generating PDF takes a long time

### ISSUE THREAD

**Issue by piotrpalek** [Studiosity/grover#85]
It's seems the page is loading for a _long_ time before anything happens, even if I have a 1s timeout, it kinda sits there and tries to load the page for more than a minute.

Any ideas what could be happening?

From what I saw it's hanging long on the `to_pdf` call.

**Comment by abrom** [comment]
Hard to say without any details. Can you share what it is you're trying to convert? How are you trying to convert it? What have you tried in terms of debugging? 

https://github.com/Studiosity/grover#debugging

**Comment by piotrpalek** [comment]
Yeah I suppose I didn't give much details, sorry :) 
It's a pretty simple (static for now) table. I'm also using paged.js there.

I've just tried to turn on debug mode:
```
debug: {
  headless: false,
  devtools: true,
}
```
and it turns out the page just doesn't load as quickly as when I open it directly as HTML (I have one endpoint which turns the page into a PDF, and one where it's just plain ruby view rendering a template).

I'm using all of this in Docker as well, maybe the issue is somehow related to it being run in Docker, I'm gonna try to investigate it. If anyone had a similar setup / problems I'd appreciate any pointers :)

**Comment by abrom** [comment]
Can you confirm you have more than one worker? If you're using the middleware to generate the PDF then of course you're going to have one worker tied up with the original PDF request and other workers then needed to respond to the other assets on your page (`paged.js` for example). If you only have one worker it'll sit there waiting for another to become available thus it'll "hang"..

**Comment by piotrpalek** [comment]
Ah, gotcha. But do I need more workers, if I have threads set up? For me workers aren't set at all in `puma.rb`, but the thread count is set to `5`

**Comment by piotrpalek** [comment]
Hah, ok it seems I've used you for rubber duck debugging a bit, sorry 😅 It seems the issue was loading the JS files. But the culprit from what I can tell is that I had my repository / files on my windows partition, and I was using WSL2 with Docker.

That caused the files to be loaded insanely slowly it seems (or maybe some other issue). Anyway, once I've cloned the repository inside WSL2 and run docker from there, it seems to work fast and nice.

Big thanks! You've been very responsive and helpful :) If I have any more issue I'll try to look into increasing the workers count first as well.

**Comment by abrom** [comment]
Workers is threads * processes, so 5 should be plenty.

Wow, that's really weird. Given Grover just uses Puppeteer/Chrome to load the content I'm surprised there would be such a difference between you loading it manually and using the automated tooling?!

Glad to hear you figured it out though

**Comment by piotrpalek** [comment]
I still had some long loading times, turned out changing `cache` to `false` speeded the process up many times. Just putting it out there in case someone has similar troubles.

**Comment by abrom** [comment]
Interesting.. I'd be happy to accept a PR to update the README with more information on this.

**Comment by piotrpalek** [comment]
I would have no issue, but I don't want to be misleading and claim it's a solution. Maybe it's just something weird in my setup or some other thing, I'd like to see if I can at least explain it somehow before recommending it to others in the README :)
