### ISSUE TITLE
Guidance using Grover with Devise

### ISSUE THREAD

**Issue by louise-r-blue** [Studiosity/grover#87]
Apologies first. This is not really an issue but I couldn't find any where else to ask this. 

Rails `6.0.3.4`
Ruby `2.7.2`

I have been experimenting with Grover (cool by the way) and find I have to add a 

`skip_before_action :authenticate_user!, only: [:show]`  (action where pdf is generated in an invoice controller)

otherwise I am unable to log in to view the pdf. 

I don't really want to do this as I don't want anyone visiting the route and viewing the invoice page. I use Devise for authentication in my admin backend.

If I missed something in your docs let me know. Thanks

**Comment by abrom** [comment]
Grover doesn't have any special needs to work with Devise.

Whether you're calling it directly or using the middleware, either case it really shouldn't matter.

If you're calling it directly in your controller your request will receive the cookies (including the session cookie) and authenticate

If you're calling it through the middleware, the middleware will forward the cookies (including the session cookie) and authenticate.

Can you test that other cookies and/or session attributes are being passed through?

**Comment by louise-r-blue** [comment]
Thanks for the info and clarification.

I haven't written test (Minitest) as of yet for testing cookies/session in the Invoice controller but can verify that inspecting  the `@request.session` and `@request.cookies` session data is being passed through.

**Comment by louise-r-blue** [comment]
abrom you can close this as I have grover (I am now calling it directly in the controller) working as it should with authentication.  Thanks :)

**Comment by abrom** [comment]
Glad to hear it. Strange that you needed to call Grover directly. I use the Grover middleware in a Rails app with Devise with authenticated routes all of the time.
