### ISSUE TITLE
Broken pipe - Can't read from worker (Worker process failed)

### ISSUE THREAD

**Issue by piotrpalek** [Studiosity/grover#89]
Hey, I have a weird issue with Grover, and it _seems_ to only happen in our production server.
Anyone experienced an error where it just says:

```
Grover::Error
Worker process failed:
```

which actually started with:

```
Errno::EPIPE
Broken pipe - Can't read from worker
```

I can't seem to get more information on this, and am wondering if / how I could debug it (can't reproduce the issue either, just happens sometimes)

**Comment by abrom** [comment]
Hi @piotrpalek 

It is something I've seen before, but like you I haven't been able to reproduce it. Happens maybe one in every 10K PDFs for me. I've gone looking into it in the past but didn't find much.

If you do find anything please do share
