### ISSUE TITLE
How can I debug JS/CSS or view the output?

### ISSUE THREAD

**Issue by Richacinas** [Studiosity/grover#9]
Hi there!

Thanks so much for the amazing work you have done with this library.

I am getting a blank page when trying to export a PDF containing some view rendered from a controller.

The thing is, that the page generated is just blank, and I can't see in the docs any way to debug.

Is there any?

Thanks

**Comment by abrom** [comment]
Given it's just using Chromium under the hood, you should be able to use Chrome/Chromium to see what the result will look like and do any debugging there.

How are you using it? As middleware? Or standalone? If it is middleware, can you confirm that it is being loaded? Check to see if `request.env['Rack-Middleware-Grover'] == 'true'` holds true in your application. 

What stack? Rails? Sinatra? Other?

**Comment by Richacinas** [comment]
Hi @abrom and thanks for the quick answer.

I'm using Rails, and your library as Standalone (I think). Here is some code:

```
html = render_to_string(action: "index_spa.html.haml", layout: 'pdf_layout')
grover = Grover.new(html, format: 'A4')
grover.to_pdf
```

Should I add chrome to the path so I can run it from bash?

**Comment by abrom** [comment]
I don't see any reason why something like that wouldn't work. It does seem like a bit of a roundabout way to get a PDF response using Grover though? Any reason not to just use it as middleware? Then any request ending in `.pdf` will be converted for you.

If that's not what you're trying to do (or maybe you only want to have that one action return a specific PDF), can you confirm that you're actually rendering the resulting PDF from the call to `to_pdf` in your controller action?

**Comment by Richacinas** [comment]
Well... there is quite a lot of JS (highcharts included) happening inside the string/html and I guess there is some error. However, I have that html saved on my disk somewhere else, and opening it with Chrome results OK.

As you guessed, I don't use the middleware because I'm running some actions when the user clicks on a button, one of them being this PDF generation. I don't see why that would help me in this case anyway..

I can confirm that I'm rendering it, because if I try with a simple html containing some text and a couple of divs, it outputs the PDF perfectly.

**Comment by abrom** [comment]
If you're able to render a basic response as a PDF it doesn't sound like you've got any environment setup or similar type issues. Sounds like there's an issue with Chromium rendering the page. Odd.. 

If you've got the HTML saved outside of the request, I'd start there. Use your console to run the code and save your PDF result to file. ie 
```
Grover.new(<your html>, <your options).to_pdf('/output/path/for/your_pdf.pdf'); nil
```
(the trailing `nil` is just so you don't end up dumping the PDF contents to your console. Not very readable!!)

Is it actually a PDF file being saved? Or a blank file?

Would you feel comfortable modifying your local gem install of Grover? If so, you can tell puppeteer (the code that controls Chromium) to not use headless mode, and you can also tell it to run in `slowMo`.

Unpack the gem, edit `lib/grover.rb#L24` and have the `launch_params` method return
```
'{headless: false, slowMo: 1000, devtools: true}'
``` 
Repack the gem then try render the PDF. You should now see the Chromium browser load and the page content display. 

If it's still going to fast, you could modify the `convert_pdf` JS (just below the `launch_params` method) and add the following just before the `return await page.pdf(options);` line:
```
await page.evaluate(() => {debugger;});
```
When you call to the Grover `to_pdf` method, Chromium should then pause execution allowing you time to see the console output.

Note, you can POST to a PDF action if you wanted. PDF requests don't need to be GET. Just set your form action to `/your/action/path.pdf`

I don't have time right now, but if you're still having trouble tomorrow I could look at adding some of the above as options. Let me know

**Comment by Richacinas** [comment]
Great. I am debugging already. By now it is ok without the 

`debugger; `

I see some errors already so by tomorrow I should have more insight about this.

Thanks!

**Comment by Richacinas** [comment]
Just found out what the problem was!

It was loading on www.example.com, and all the assets as well, so I just used the display_url option to set the base url of my project and everything is working as expected. Now I'm dealing with latin chars not being properly displayed..

Thanks so much for your help

**Comment by abrom** [comment]
Ahh.. ok. Interesting that this works.. in the middleware I use the following to pre-process the HTML and replace all of the relative URLs with absolute:
```
html = Grover::HTMLPreprocessor.process html, root_url, protocol
```
But hey.. if Chromium is happy to use the display_url host, why not :)

I do have a [comment about the `display_url`](https://github.com/Studiosity/grover#page-url-for-middleware-requests-or-passing-through-raw-html) in the README, but maybe it needs some expanding to make it clearer.

Good catch 👍 

I'll have a think about the debugging options so that hopefully it is easier next time

**Comment by Richacinas** [comment]
Thanks a lot. I'll go ahead and close this issue then.
