### ISSUE TITLE
Heroku slug size

### ISSUE THREAD

**Issue by adrienpoly** [Studiosity/grover#91]
Hello 

Thanks for this great Gem. 

On one application I am running into an issue when deploying Grover to Heroku my slug size gets above the 500Mb allowed and therefore I am unable to deploy.

I have tried purging the cache on Heroku and several tutos to reduce the slug size but without any major success.

Looking more into details of my slug I realized Puppeteer download a Chrome version of around 300Mb. I looked into using `puppeteer-core` with a [chrome build pack](https://github.com/heroku/heroku-buildpack-google-chrome) to see if this could help. I could specify `puppeteer-core`, but I am running into an issue on how to tell Grover to use the Chrome install coming from the build pack.

Do you have some guidance on how I could do this or other suggestion for working with Heroku and minimizing the slug size with Puppeteer

Thanks

**Comment by abrom** [comment]
Hi @adrienpoly,

I can't say I've used Grover with Heroku, but that sounds like quite a pain. Have you tried specifying the path with the `executable_path` option?

This setting simply specifies the `executablePath` when calling `puppeteer.launch`. See https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#puppeteerlaunchoptions

**Comment by adrienpoly** [comment]
Hello @abrom 

Thanks for pointing me in the correct direction it helped me a lot.
I got a working solution now

**Comment by adrienpoly** [comment]
Hello @abrom

Thanks for pointing me in the correct direction it helped me a lot.
I got a working solution now

What I did :


Add Chrome buildpack
```
heroku buildpacks:add heroku/google-chrome --index=1 [--remote yourappname]
```

Add Node/JS buildpack
```
heroku buildpacks:add heroku/nodejs --index=2 [--remote yourappname]
``` 

Add Puppeteer buildpack (not sure if I still really need it or if Chrome build pack is enough will try at some point without it)
```
heroku buildpacks:add jontewks/puppeteer --index=3 [--remote yourappname]
```

**Set the ENV variable to prevent downloading Chrominium**
```
heroku config:set PUPPETEER_SKIP_DOWNLOAD=true [--remote yourappname]
```

Configure the executable path
```ruby
Grover.configure do |config|
  config.options = {
    ...
    executable_path: "google-chrome"
  }
end
```

### Puppeteer Core

Not sure if you are interested I have also a branch that supports puppeteer-core (first require `puppeteer` and fallback to `puppeteer-core`). I can open a PR on that if you feel that would be a valuable addition.
From what I could see using `core` is very similar to setting the env PUPPETEER_SKIP_DOWNLOAD to `true`

**Comment by abrom** [comment]
hi @adrienpoly, good to hear.

Happy to accept a PR. Feel free to also update the README to expand on the Heroku section if you feel that could be explained better/differently.

**Comment by markymc** [comment]
@adrienpoly 

> Add Puppeteer buildpack (not sure if I still really need it or if Chrome build pack is enough will try at some point without it)
>
> `heroku buildpacks:add jontewks/puppeteer --index=3 [--remote yourappname]`

Just wondering if you worked out if this is needed or not? Would be helpful for others I'd think. Thanks! :)

**Comment by adrienpoly** [comment]
@markymc  no I never investigated more that solution as we stopped using Puppeteer directly in Heroku, it takes too much ressources. Unless you have a huge dyno I think it is not a viable solution in the Heroku world. 
We ended up using `browserless.io` remote Puppeteer

**Comment by markymc** [comment]
@adrienpoly Thanks! Seems fairly well-priced compared the the hassle and cost of setting Puppeteer up on a dedicated Heroku instance for my use case (screenshotting dynamic OG images). 👍

**Comment by paulRbr** [comment]
Thanks for the solution @adrienpoly!

> Just wondering if you worked out if this is needed or not? Would be helpful for others I'd think. Thanks! :)

I have set it up without the `puppeteer` buildpack and it works well with only those:
```
> heroku buildpacks -a my-app
=== my-app Buildpack URLs 
1. heroku/google-chrome                       
2. heroku/nodejs
```

**Comment by chalmagean** [comment]
The `PUPPETEER_SKIP_DOWNLOAD` option doesn't seem to do much regarding slug size. Is there another way to make the slug smaller?
