### ISSUE TITLE
Call Grover.new('').to_pdf gets stuck forever

### ISSUE THREAD

**Issue by alexwbuschle** [Studiosity/grover#94]
Happy path:
  - When you call `to_pdf` with a value with content (even spaces), it returns the PDF

Bad path:
  - When you call `to_pdf` with a nil value, it returns an error. I don't know if it should return an error or change it to a blank value and return the PDF.
  - When you call `to_pdf` with an empty value (`Grover.new('').to_pdf`), it gets frozen until it reaches the timeout.

**Comment by abrom** [comment]
Hmm interesting. I can see the `nil` value is getting caught up in the options builder.. wouldn't be hard to add a guard to prevent that, or simply call `to_s` on the attribute in the initialiser. Regarding the empty string, I suspect that comes down to how puppeteer handles the request interception being responded with an empty body. Likely it is assuming there was no response, thus keeps waiting for one (and finally times out). Could just have something that sends through a single space if the input is empty?

https://github.com/puppeteer/puppeteer/blob/v5.5.0/docs/api.md#httprequestrespondresponse

I'd happy take input on how you think these cases should be handled. I'd also happily accept a PR to fix it along with some specs
