### ISSUE TITLE
Cannot find module 'puppeteer'.

### ISSUE THREAD

**Issue by ponwink** [Studiosity/grover#96]
Hello, There is an error in my rails project

```
Grover::DependencyError (Cannot find module 'puppeteer'. You need to add it to '/package.json' and run 'npm install'):
```

Environment:
> Ruby 2.7.1
> Rails 6.0.3.2
> Grover 0.13.3
> in production

```
# package-lock.json
  "puppeteer": {
      "version": "5.5.0",
  },
```

However, if you modify it as follows, no problem

```
# js/processor.js
// var puppeteer = require(require.resolve('puppeteer', { paths: Module._nodeModulePaths(process.cwd()) }));
var puppeteer = require('puppeteer');
```

Do you have any other solutions?

**Comment by abrom** [comment]
that might work for you, but it won't work for anyone else ;)

It sounds like you have your node setup in a non-standard location (ie not in the root of your project). If you do that, Grover won't know where to look for puppeteer. You can specify the location of your node setup using the `root_path` configuration option if need be.

**Comment by ponwink** [comment]
Thanks! it's solved.

```
# config/initializers/grover.rb
Grover.configure do |config|
  config.options = {
    root_path: '/home/user/my_rails_project'
  }
end
```

**Comment by abrom** [comment]
It sounds like you're possibly launching your rails app from some other directory (other than the root of the project?)

Grover defaults the root path to the place you launched the app from. ie:

https://github.com/Studiosity/grover/blob/main/lib/grover.rb#L130

**Comment by ponwink** [comment]
Thanks! I checked it up.

```
$ rails server -e production -p 3000 -d -b 0.0.0.0
```

I used to run rails server with the `daemonize` option, can't find project root path.
I fixed it as follows and solved it.

```
# config/puma.rb
daemonize true
```

```
$ rails server -e production -p 3000 -b 0.0.0.0
```
