### ISSUE TITLE
Ruby 3 Support

### ISSUE THREAD

**Issue by jnimety** [Studiosity/grover#98]
Is there any work in progress for Ruby 3.0 support?

**Comment by abrom** [comment]
No, but i'm not aware of any incompatibilities. Have you come across an issue?

**Comment by jnimety** [comment]
The only thing I'm aware of is that the gemspec excludes ruby 3.

**Comment by abrom** [comment]
[v0.14.1](https://rubygems.org/gems/grover/versions/0.14.1) has been released allowing for Ruby 3.0 (no actual code change, just bumped up the required Ruby version)

**Comment by jnimety** [comment]
Thanks for the quick turnaround!
